"""Trigger cache for procedure advisor hook.

Generates and loads a YAML file (the human-readable source of truth) plus a
colocated ``.json`` sidecar of identical content, containing CORE and
ADVISORY-tier procedures with their tool triggers and context patterns. The
PreToolUse hook script reads this cache instead of querying the database (hook
timeout is ~2s, DB access is risky) — and prefers the JSON sidecar so it never
pays the ~40ms ``import yaml`` cost on the every-tool-call hot path.

ADVISORY procedures with tool triggers are included because they are mature
(5+ successes, 75%+ confidence) and warrant preemptive advisory.

Cache is regenerated by:
- seed_procedures.py (initial population)
- promoter.py (on tier changes)
"""

from __future__ import annotations

import contextlib
import json
import logging
import os
import tempfile
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

# $GENESIS_PROCEDURE_TRIGGERS overrides the default cache location (tests /
# relocated installs); the PreToolUse advisor reads the same env var.
_CACHE_PATH = Path(
    os.environ.get("GENESIS_PROCEDURE_TRIGGERS")
    or (Path(__file__).resolve().parents[4] / "config" / "procedure_triggers.yaml")
)
# Colocated stdlib-loadable sidecar of the same content, so the hook can read it
# without importing yaml. Written after the YAML, so its mtime is >= the YAML's.
_JSON_CACHE_PATH = _CACHE_PATH.with_suffix(".json")


def get_cache_path() -> Path:
    return _CACHE_PATH


def get_json_cache_path() -> Path:
    return _JSON_CACHE_PATH


def _atomic_write(path: Path, text: str) -> None:
    """Write ``text`` to ``path`` atomically (temp file in the same dir + rename)
    so a concurrent hook read never sees a partial file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=path.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(text)
        os.rename(tmp_path, str(path))
    except Exception:
        with contextlib.suppress(OSError):
            os.unlink(tmp_path)
        raise


async def regenerate(db: object) -> int:
    """Regenerate trigger cache from CORE+ADVISORY procedures in the database.

    Uses atomic write (temp file + rename) to avoid race conditions
    with the hook reading the file.

    Returns the number of triggers written.
    """
    from genesis.db.crud import procedural

    # Include both CORE and ADVISORY procedures — ADVISORY with tool triggers
    # are mature enough (5+ successes, 75%+ confidence) to warrant hook advisories.
    rows_core = await procedural.list_by_tier(db, "CORE")  # type: ignore[arg-type]
    rows_advisory = await procedural.list_by_tier(db, "ADVISORY")  # type: ignore[arg-type]
    rows = rows_core + rows_advisory
    triggers = []
    for row in rows:
        tool_trigger = json.loads(row["tool_trigger"]) if row.get("tool_trigger") else None
        if not tool_trigger:
            continue

        # Build context patterns from context_tags for regex matching
        context_patterns = json.loads(row["context_tags"]) if isinstance(row["context_tags"], str) else row["context_tags"]

        triggers.append({
            "tool": tool_trigger,
            "context_patterns": context_patterns,
            "procedure_id": row["id"],
            "task_type": row["task_type"],
            "principle": row["principle"],
            "steps": json.loads(row["steps"]) if isinstance(row["steps"], str) else row["steps"],
            "confidence": row["confidence"],
        })

    cache_data = {
        "generated_at": __import__("datetime").datetime.now(__import__("datetime").UTC).isoformat(),
        "triggers": triggers,
    }

    # Write the YAML source of truth, then the JSON sidecar (same content). JSON
    # is written last so its mtime is >= the YAML's — the hook only trusts the
    # sidecar when it is at least as fresh as the YAML.
    _atomic_write(_CACHE_PATH, yaml.dump(cache_data, default_flow_style=False, sort_keys=False))
    _atomic_write(_JSON_CACHE_PATH, json.dumps(cache_data))

    logger.info("Regenerated procedure trigger cache: %d triggers", len(triggers))
    return len(triggers)


def load() -> list[dict]:
    """Load triggers from YAML cache. Returns empty list on any error."""
    try:
        data = yaml.safe_load(_CACHE_PATH.read_text())
        return data.get("triggers", []) if data else []
    except Exception:
        return []
