"""Canonical transcript filter + delta parsing (session-manager PR-3).

Includes the parity test pinning the PreCompact hook's private stdlib
duplicate of the typed-prompt filter to this module (the ``_charter_md``
precedent: intentional duplicate, byte-equivalent behavior, drift fails
CI).
"""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

from genesis.session_awareness.transcript import (
    NON_PROMPT_PREFIXES,
    entry_text,
    parse_delta,
    typed_prompt_text,
)

_HOOK_PATH = Path(__file__).parents[2] / "scripts" / "genesis_precompact.py"
_pc_spec = importlib.util.spec_from_file_location("genesis_precompact_parity", _HOOK_PATH)
_pc = importlib.util.module_from_spec(_pc_spec)
_pc_spec.loader.exec_module(_pc)


def _typed(text: str, ts: str = "2026-06-30T15:21:06.000Z", **extra) -> dict:
    entry = {
        "type": "user",
        "isSidechain": False,
        "userType": "external",
        "uuid": f"u-{abs(hash(text)) % 10**8}",
        "message": {"role": "user", "content": text},
        "timestamp": ts,
    }
    entry.update(extra)
    return entry


def _assistant(text: str, **extra) -> dict:
    entry = {
        "type": "assistant",
        "message": {
            "role": "assistant",
            "content": [{"type": "text", "text": text}],
        },
        "timestamp": "2026-06-30T15:21:05.000Z",
    }
    entry.update(extra)
    return entry


def _tool_result() -> dict:
    return {
        "type": "user",
        "message": {
            "role": "user",
            "content": [{"type": "tool_result", "tool_use_id": "x", "content": "ok"}],
        },
        "timestamp": "2026-06-30T15:21:03.000Z",
    }


# The full behavioral matrix both filters must agree on. Shapes verified
# against live transcripts 2026-07-13/14 (synthetic text stand-ins).
PARITY_ENTRIES = [
    _typed("Let's fix the flaky retry logic in the pipeline."),
    _typed("/compact"),
    _typed("/model"),
    _typed("[Request interrupted by user for tool use]"),
    _typed("This session is being continued from a previous conversation."),
    _typed("<command-name>/model</command-name>"),
    _typed("<local-command-stdout>ok</local-command-stdout>"),
    _typed("Caveat: The messages below were generated by the user while running local commands."),
    _typed("<bash-input>ls</bash-input>"),
    _typed("/etc/hosts keeps getting clobbered, take a look"),
    _typed("marked prompt", promptSource="typed"),
    _typed("queued prompt", promptSource="queued"),
    _typed("harness notification", promptSource="system"),
    _typed("marked command", promptSource="command"),
    _typed("sidechain prompt", isSidechain=True),
    _typed("meta prompt", isMeta=True),
    _typed("summary text", isCompactSummary=True),
    _tool_result(),
    _assistant("assistant text"),
    {"type": "mode", "mode": "default"},
    {
        "type": "user",
        "message": {
            "role": "user",
            "content": [
                {"type": "image", "source": {}},
                {"type": "text", "text": "what is in this screenshot?"},
            ],
        },
        "timestamp": "2026-06-30T15:21:06.000Z",
    },
]


def test_filter_parity_with_hook_duplicate():
    """The hook's private copy and the canonical module must agree on
    every entry shape — drift here fails CI."""
    for entry in PARITY_ENTRIES:
        assert typed_prompt_text(entry) == _pc._typed_prompt_text(entry), entry


def test_prefix_list_parity_with_hook():
    assert tuple(NON_PROMPT_PREFIXES) == tuple(_pc._NON_PROMPT_PREFIXES)


def test_typed_prompt_admits_genuine():
    assert typed_prompt_text(_typed("real prompt")) == "real prompt"


def test_typed_prompt_rejects_commands_and_markers():
    assert typed_prompt_text(_typed("/compact")) is None
    assert typed_prompt_text(_typed("[Request interrupted by user]")) is None
    assert typed_prompt_text(_typed("cmd", promptSource="command")) is None
    assert typed_prompt_text(_typed("notify", promptSource="system")) is None


def test_typed_prompt_admits_queued():
    """Queued prompts (typed mid-turn) are genuine human prompts —
    ratification messages ("yes, do that") are overrepresented there."""
    assert typed_prompt_text(_typed("yes, do that", promptSource="queued")) == "yes, do that"


def test_typed_prompt_slash_prose_survives():
    text = "/etc/hosts keeps getting clobbered"
    assert typed_prompt_text(_typed(text)) == text


def test_entry_text_rejects_tool_result_lists():
    assert entry_text([{"type": "tool_result", "content": "x"}]) is None
    assert entry_text([{"type": "text", "text": "hi"}]) == "hi"
    assert entry_text("plain") == "plain"
    assert entry_text(None) is None


# ── parse_delta ──────────────────────────────────────────────────────────


def _write(path: Path, entries: list[dict]) -> Path:
    path.write_text("\n".join(json.dumps(e) for e in entries) + "\n")
    return path


def test_parse_delta_full_file(tmp_path):
    entries = [
        _assistant("I propose we ship the widget refactor now."),
        {"type": "mode", "mode": "default"},
        _tool_result(),
        _typed("yes, do that — and add the rollback lever"),
        _typed("/compact"),
    ]
    t = _write(tmp_path / "s.jsonl", entries)
    turns = parse_delta(t, 0, t.stat().st_size)
    assert len(turns) == 1
    turn = turns[0]
    assert turn["user_text"] == "yes, do that — and add the rollback lever"
    assert turn["assistant_snippet"] == "I propose we ship the widget refactor now."
    assert turn["turn_ref"].startswith("u-")
    assert turn["ts"] == "2026-06-30T15:21:06.000Z"


def test_parse_delta_snippet_scans_back_past_noise(tmp_path):
    noise = [{"type": "mode", "mode": "default"} for _ in range(20)]
    entries = [_assistant("the proposal"), *noise, _typed("agreed")]
    t = _write(tmp_path / "s.jsonl", entries)
    turns = parse_delta(t, 0, t.stat().st_size)
    assert turns[0]["assistant_snippet"] == "the proposal"


def test_parse_delta_snippet_absent_beyond_scanback(tmp_path):
    noise = [{"type": "mode", "mode": "default"} for _ in range(60)]
    entries = [_assistant("too far back"), *noise, _typed("agreed")]
    t = _write(tmp_path / "s.jsonl", entries)
    turns = parse_delta(t, 0, t.stat().st_size)
    assert turns[0]["assistant_snippet"] == ""


def test_parse_delta_snippet_skips_sidechain_assistant(tmp_path):
    entries = [
        _assistant("real assistant text"),
        _assistant("subagent chatter", isSidechain=True),
        _typed("ok go"),
    ]
    t = _write(tmp_path / "s.jsonl", entries)
    turns = parse_delta(t, 0, t.stat().st_size)
    assert turns[0]["assistant_snippet"] == "real assistant text"


def test_parse_delta_byte_window_and_torn_line(tmp_path):
    """A start byte landing mid-line skips the torn line; entries past
    end_byte are excluded."""
    early = _typed("early prompt", ts="2026-06-30T15:00:00.000Z")
    mid = _typed("mid prompt", ts="2026-06-30T15:10:00.000Z")
    late = _typed("late prompt", ts="2026-06-30T15:20:00.000Z")
    t = _write(tmp_path / "s.jsonl", [early, mid, late])
    raw = t.read_bytes()
    early_end = raw.find(b"\n") + 1
    mid_end = raw.find(b"\n", early_end) + 1
    # start inside the first line (torn), end after the second line
    turns = parse_delta(t, 5, mid_end)
    assert [x["user_text"] for x in turns] == ["mid prompt"]
    # clean start at a line boundary sees the rest
    turns = parse_delta(t, early_end, t.stat().st_size)
    assert [x["user_text"] for x in turns] == ["mid prompt", "late prompt"]


def test_parse_delta_caps_user_text(tmp_path):
    t = _write(tmp_path / "s.jsonl", [_typed("x" * 5000)])
    turns = parse_delta(t, 0, t.stat().st_size, max_user_chars=100)
    assert len(turns[0]["user_text"]) == 100


def test_parse_delta_turn_ref_falls_back_to_timestamp(tmp_path):
    entry = _typed("no uuid prompt")
    del entry["uuid"]
    t = _write(tmp_path / "s.jsonl", [entry])
    turns = parse_delta(t, 0, t.stat().st_size)
    assert turns[0]["turn_ref"] == "2026-06-30T15:21:06.000Z"


def test_parse_delta_tolerates_garbage_lines(tmp_path):
    t = tmp_path / "s.jsonl"
    t.write_text("not json\n[1,2]\n" + json.dumps(_typed("hi")) + "\n")
    turns = parse_delta(t, 0, t.stat().st_size)
    assert [x["user_text"] for x in turns] == ["hi"]
