"""Tests for procedure_advisor._load_triggers JSON-sidecar fast path (LOW-c).

The advisor is a PreToolUse hook (fresh process per tool call), so ``import
yaml`` (~40ms) on every call was avoidable. It now prefers a JSON sidecar
written by trigger_cache.regenerate, falling back to the YAML source of truth
when the sidecar is missing, corrupt, or older than the YAML.

These load the script as a module and drive ``_load_triggers`` directly, so the
mtime/branch logic is tested precisely (no subprocess, no seeding).
"""

from __future__ import annotations

import importlib.util
import json
import os
from pathlib import Path

_SCRIPT = Path(__file__).resolve().parents[2] / "scripts" / "procedure_advisor.py"


def _load_module():
    spec = importlib.util.spec_from_file_location("_procedure_advisor_under_test", _SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _point(mod, monkeypatch, yaml_p: Path, json_p: Path) -> None:
    monkeypatch.setattr(mod, "_CACHE_PATH", yaml_p)
    monkeypatch.setattr(mod, "_JSON_CACHE_PATH", json_p)


def _yaml_triggers(task_type: str) -> str:
    # Minimal valid YAML the loader understands (triggers: list).
    return f"triggers:\n- tool: [Bash]\n  task_type: {task_type}\n"


def _json_triggers(task_type: str) -> str:
    return json.dumps({"triggers": [{"tool": ["Bash"], "task_type": task_type}]})


def _set_order(older: Path, newer: Path) -> None:
    """Force `older` to have a strictly smaller mtime than `newer`."""
    os.utime(older, ns=(1_000_000_000, 1_000_000_000))
    os.utime(newer, ns=(2_000_000_000, 2_000_000_000))


def test_prefers_json_when_fresh(tmp_path, monkeypatch):
    mod = _load_module()
    yaml_p = tmp_path / "c.yaml"
    json_p = tmp_path / "c.json"
    yaml_p.write_text(_yaml_triggers("from_yaml"))
    json_p.write_text(_json_triggers("from_json"))
    _set_order(older=yaml_p, newer=json_p)  # json newer → fast path
    _point(mod, monkeypatch, yaml_p, json_p)

    trig = mod._load_triggers()
    assert len(trig) == 1 and trig[0]["task_type"] == "from_json"


def test_falls_back_to_yaml_when_json_missing(tmp_path, monkeypatch):
    mod = _load_module()
    yaml_p = tmp_path / "c.yaml"
    json_p = tmp_path / "c.json"  # never written
    yaml_p.write_text(_yaml_triggers("from_yaml"))
    _point(mod, monkeypatch, yaml_p, json_p)

    trig = mod._load_triggers()
    assert len(trig) == 1 and trig[0]["task_type"] == "from_yaml"


def test_falls_back_to_yaml_when_json_older(tmp_path, monkeypatch):
    """A YAML regenerated by an old generator (no matching JSON refresh) must not
    be served stale from an older sidecar."""
    mod = _load_module()
    yaml_p = tmp_path / "c.yaml"
    json_p = tmp_path / "c.json"
    yaml_p.write_text(_yaml_triggers("fresh_yaml"))
    json_p.write_text(_json_triggers("stale_json"))
    _set_order(older=json_p, newer=yaml_p)  # yaml newer → ignore json
    _point(mod, monkeypatch, yaml_p, json_p)

    trig = mod._load_triggers()
    assert trig[0]["task_type"] == "fresh_yaml"


def test_falls_back_to_yaml_when_json_corrupt(tmp_path, monkeypatch):
    mod = _load_module()
    yaml_p = tmp_path / "c.yaml"
    json_p = tmp_path / "c.json"
    yaml_p.write_text(_yaml_triggers("from_yaml"))
    json_p.write_text("{not valid json")
    _set_order(older=yaml_p, newer=json_p)  # json newer but corrupt
    _point(mod, monkeypatch, yaml_p, json_p)

    trig = mod._load_triggers()
    assert trig[0]["task_type"] == "from_yaml"


def test_empty_when_neither_exists(tmp_path, monkeypatch):
    mod = _load_module()
    _point(mod, monkeypatch, tmp_path / "none.yaml", tmp_path / "none.json")
    assert mod._load_triggers() == []
