"""LLM annotation layer — the operational-gotcha notes per fact section.

Annotations are generated by the router (call site 46, strong-first chain —
free-model output proved too weak for judgment at call site 37) and PINNED to
the fact-section hash they were derived from:

- hash unchanged        → annotation reused, zero LLM spend
- hash changed/missing  → regenerate that section only
- regeneration fails    → old annotation kept with its old source_hash; the
  renderer derives staleness (source_hash != section hash) at render time —
  never stored, so the file can't lie.
"""

from __future__ import annotations

import asyncio
import json
import logging
from datetime import UTC, datetime
from typing import Any

logger = logging.getLogger(__name__)

CALL_SITE_ID = "46_infra_annotation"

# Two concurrent annotation calls: enough to hide latency across ~15 sections
# on a cold start without stampeding a provider.
_CONCURRENCY = 2

_PROMPT = """\
You are annotating one section of an infrastructure self-knowledge profile for
Genesis, an autonomous agent that runs on this machine. Your notes are read by
operators and by diagnostic agents during incidents.

Profile summary: {summary}

Section: {section}
Facts (stable configuration/topology):
{facts}
Current readings (volatile, for context only):
{metrics}

Previous annotation for this section (may be outdated):
{previous}

Write 2-6 bullet points of OPERATIONAL GOTCHAS grounded in these specific
values: failure modes this configuration enables, limits that will bite,
mismatches between components, and what to check first when this section is
implicated in an incident. Be concrete and falsifiable — name the value and
the consequence. No generic advice, no praise, no restating the facts.
Output ONLY the bullet lines, each starting with "- "."""


def _annotation_entry(text: str, source_hash: str, model: str | None) -> dict[str, Any]:
    return {
        "annotation": text,
        "source_hash": source_hash,
        "generated_at": datetime.now(UTC).isoformat(),
        "model": model,
        "call_site": CALL_SITE_ID,
    }


async def regenerate_annotations(
    *,
    profile: dict[str, Any],
    annotations: dict[str, Any],
    router,
    summary: str,
) -> dict[str, Any]:
    """Return an updated annotations mapping for ``profile``.

    Only sections whose hash moved (or that lack an annotation) are
    regenerated; failures keep the previous entry untouched.
    """
    if router is None:
        return annotations

    sections = profile.get("sections", {})
    existing = annotations.get("sections", {})
    updated = dict(existing)

    stale = [
        (name, section)
        for name, section in sections.items()
        if section.get("status") == "ok"
        and section.get("hash")
        and existing.get(name, {}).get("source_hash") != section.get("hash")
    ]
    if not stale:
        return annotations

    semaphore = asyncio.Semaphore(_CONCURRENCY)

    async def _one(name: str, section: dict[str, Any]) -> None:
        prompt = _PROMPT.format(
            summary=summary,
            section=name,
            facts=json.dumps(section.get("facts", {}), indent=2, default=str)[:6000],
            metrics=json.dumps(section.get("metrics", {}), indent=2, default=str)[:2000],
            previous=existing.get(name, {}).get("annotation") or "(none)",
        )
        async with semaphore:
            try:
                response = await router.call(
                    call_site_id=CALL_SITE_ID,
                    messages=[{"role": "user", "content": prompt}],
                )
            except Exception:
                logger.warning(
                    "infra_profile: annotation call failed for %s — keeping previous",
                    name,
                    exc_info=True,
                )
                return
        if not response:
            logger.warning("infra_profile: empty annotation response for %s", name)
            return
        text = (
            response.get("content", "") if isinstance(response, dict) else str(response)
        ).strip()
        if not text:
            return
        model = response.get("model") if isinstance(response, dict) else None
        updated[name] = _annotation_entry(text, section["hash"], model)

    await asyncio.gather(*(_one(name, section) for name, section in stale))

    return {"schema_version": 1, "sections": updated}
