"""Tests for the PreCompact charter hook + SessionStart charter injection.

Covers scripts/genesis_precompact.py (origin extraction, charter lifecycle,
skip guards, fail-open) and the charter emission block in
scripts/genesis_session_context.py.

Fixture entry shapes mirror REAL transcript entries (verified empirically
against live ~/.claude/projects transcripts, 2026-07-13): typed prompts are
type=="user" with plain-string content; tool results are content-lists of
tool_result blocks; skill/hook injections carry isMeta; compaction summaries
carry isCompactSummary + isVisibleInTranscriptOnly; subagent traffic carries
isSidechain. promptSource exists only on modern (>=2.1.201) entries — "typed"/
"queued" on genuine prompts, "system" on harness notifications, ABSENT on
bare slash-command records and all pre-July-2026 entries (verified 2026-07-14).
"""

from __future__ import annotations

import importlib.util
import io
import json
import sqlite3
from pathlib import Path

import pytest

# Load the hook scripts as modules (not packages — use importlib)
_SCRIPTS_DIR = Path(__file__).resolve().parent.parent.parent / "scripts"

_pc_spec = importlib.util.spec_from_file_location(
    "genesis_precompact", _SCRIPTS_DIR / "genesis_precompact.py"
)
_pc = importlib.util.module_from_spec(_pc_spec)
_pc_spec.loader.exec_module(_pc)

_ctx_spec = importlib.util.spec_from_file_location(
    "genesis_session_context", _SCRIPTS_DIR / "genesis_session_context.py"
)
_ctx = importlib.util.module_from_spec(_ctx_spec)
_ctx_spec.loader.exec_module(_ctx)


# ── fixture builders (real transcript shapes) ──────────────────────────────


def _attachment_line() -> dict:
    return {"type": "attachment", "attachment": {}, "timestamp": "2026-06-30T15:21:00.000Z"}


def _meta_caveat_line() -> dict:
    return {
        "type": "user",
        "isMeta": True,
        "message": {
            "role": "user",
            "content": "Caveat: The messages below were generated by the user while running local commands.",
        },
        "timestamp": "2026-06-30T15:21:01.000Z",
    }


def _command_line() -> dict:
    return {
        "type": "user",
        "message": {"role": "user", "content": "<command-name>/model</command-name>"},
        "timestamp": "2026-06-30T15:21:02.000Z",
    }


def _tool_result_line() -> dict:
    return {
        "type": "user",
        "message": {
            "role": "user",
            "content": [{"type": "tool_result", "tool_use_id": "x", "content": "ok"}],
        },
        "timestamp": "2026-06-30T15:21:03.000Z",
    }


def _compact_summary_line() -> dict:
    return {
        "type": "user",
        "isCompactSummary": True,
        "isVisibleInTranscriptOnly": True,
        "message": {
            "role": "user",
            "content": "This session is being continued from a previous conversation that ran out of context.",
        },
        "timestamp": "2026-06-30T15:21:04.000Z",
    }


def _sidechain_line() -> dict:
    return {
        "type": "user",
        "isSidechain": True,
        "message": {"role": "user", "content": "subagent prompt text"},
        "timestamp": "2026-06-30T15:21:05.000Z",
    }


def _typed_line(
    text: str = "Let's take a look at the flaky retry logic in the ingestion pipeline.",
) -> dict:
    return {
        "type": "user",
        "isSidechain": False,
        "userType": "external",
        "message": {"role": "user", "content": text},
        "timestamp": "2026-06-30T15:21:06.000Z",
    }


def _write_transcript(path: Path, entries: list[dict]) -> Path:
    path.write_text("\n".join(json.dumps(e) for e in entries) + "\n")
    return path


def _realistic_head(
    typed_text: str = "Let's take a look at the flaky retry logic in the ingestion pipeline.",
) -> list[dict]:
    """The real pre-prompt noise ordering observed in live transcripts."""
    return [
        {"type": "last-prompt", "leafUuid": "x"},
        {"type": "mode", "mode": "default"},
        _attachment_line(),
        _attachment_line(),
        _meta_caveat_line(),
        _command_line(),
        _typed_line(typed_text),
        _tool_result_line(),
    ]


# ── origin extraction ───────────────────────────────────────────────────────


def test_extract_origin_skips_noise_and_finds_first_typed(tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    origin = _pc._extract_origin(t)
    assert origin is not None
    assert origin["origin_prompt"] == (
        "Let's take a look at the flaky retry logic in the ingestion pipeline."
    )
    assert origin["origin_ts"] == "2026-06-30T15:21:06.000Z"


def test_extract_origin_skips_compact_summary_head(tmp_path):
    """A summary-continued session must not charter the summary as origin."""
    entries = [
        _attachment_line(),
        _compact_summary_line(),
        _typed_line("Alright, talk to me about this."),
    ]
    t = _write_transcript(tmp_path / "s.jsonl", entries)
    origin = _pc._extract_origin(t)
    assert origin["origin_prompt"] == "Alright, talk to me about this."


def test_extract_origin_skips_sidechain(tmp_path):
    entries = [_sidechain_line(), _typed_line("real prompt")]
    t = _write_transcript(tmp_path / "s.jsonl", entries)
    assert _pc._extract_origin(t)["origin_prompt"] == "real prompt"


def test_extract_origin_accepts_text_block_list(tmp_path):
    """Typed prompts with attachments arrive as content-block lists."""
    entries = [
        {
            "type": "user",
            "message": {
                "role": "user",
                "content": [
                    {"type": "image", "source": {}},
                    {"type": "text", "text": "what is in this screenshot?"},
                ],
            },
            "timestamp": "2026-06-30T15:21:06.000Z",
        }
    ]
    t = _write_transcript(tmp_path / "s.jsonl", entries)
    assert _pc._extract_origin(t)["origin_prompt"] == "what is in this screenshot?"


def _bare_command_line(text: str = "/compact") -> dict:
    """Bare slash-command record: plain string content, NO XML wrapper,
    NO promptSource key (real shape verified on a live CC 2.1.201
    transcript, 2026-07-14 — these pass every flag filter)."""
    return {
        "type": "user",
        "isSidechain": False,
        "userType": "external",
        "entrypoint": "cli",
        "message": {"role": "user", "content": text},
        "timestamp": "2026-06-30T15:21:02.500Z",
    }


def test_extract_origin_skips_bare_slash_command(tmp_path):
    """A session whose first user entry is a bare '/compact' record must
    not charter the command as its origin."""
    entries = [_bare_command_line(), _typed_line("the real first prompt")]
    t = _write_transcript(tmp_path / "s.jsonl", entries)
    assert _pc._extract_origin(t)["origin_prompt"] == "the real first prompt"


def test_extract_origin_skips_interrupt_marker(tmp_path):
    entries = [
        _bare_command_line("[Request interrupted by user for tool use]"),
        _typed_line("the real first prompt"),
    ]
    t = _write_transcript(tmp_path / "s.jsonl", entries)
    assert _pc._extract_origin(t)["origin_prompt"] == "the real first prompt"


def test_extract_origin_honors_prompt_source_marker(tmp_path):
    """Modern CC marks genuine prompts promptSource='typed'; an entry
    carrying any other value is never an origin, whatever its text."""
    cmd = _bare_command_line("looks like a real prompt but is not")
    cmd["promptSource"] = "command"
    genuine = _typed_line("the real first prompt")
    genuine["promptSource"] = "typed"
    t = _write_transcript(tmp_path / "s.jsonl", [cmd, genuine])
    assert _pc._extract_origin(t)["origin_prompt"] == "the real first prompt"


def test_extract_origin_slash_prefix_prose_still_admitted(tmp_path):
    """Only single-token slash commands are excluded — a genuine prompt
    that merely starts with '/' survives."""
    entries = [_typed_line("/etc/hosts keeps getting clobbered, take a look")]
    t = _write_transcript(tmp_path / "s.jsonl", entries)
    assert _pc._extract_origin(t)["origin_prompt"] == (
        "/etc/hosts keeps getting clobbered, take a look"
    )


def test_extract_origin_none_when_no_typed_prompt(tmp_path):
    entries = [_attachment_line(), _tool_result_line(), _meta_caveat_line()]
    t = _write_transcript(tmp_path / "s.jsonl", entries)
    assert _pc._extract_origin(t) is None


def test_extract_origin_survives_malformed_lines(tmp_path):
    t = tmp_path / "s.jsonl"
    t.write_text('not json at all\n{"type": "mode"}\n' + json.dumps(_typed_line("hi")) + "\n")
    assert _pc._extract_origin(t)["origin_prompt"] == "hi"


# ── charter lifecycle via main() ────────────────────────────────────────────


def _make_db(tmp_path: Path) -> Path:
    """tmp GENESIS_REPO_ROOT with data/genesis.db carrying the 0058 tables.

    Uses the canonical DDL from db/schema/_tables.py so the fresh-DB mirror
    is exactly what the hook is exercised against. Idempotent.
    """
    from genesis.db.schema._tables import TABLES

    root = tmp_path / "repo"
    (root / "data").mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(root / "data" / "genesis.db")
    conn.execute(TABLES["session_charters"])
    conn.execute(TABLES["session_ledger"])
    conn.commit()
    conn.close()
    return root


def _db_row(tmp_path: Path, session_id: str) -> dict | None:
    conn = sqlite3.connect(tmp_path / "repo" / "data" / "genesis.db")
    conn.row_factory = sqlite3.Row
    row = conn.execute(
        "SELECT * FROM session_charters WHERE session_id = ?", (session_id,)
    ).fetchone()
    conn.close()
    return dict(row) if row else None


def _run_main(
    monkeypatch,
    tmp_path,
    *,
    session_id: str,
    transcript: Path | str,
    trigger: str = "manual",
    with_db: bool = True,
):
    """Invoke the hook main() the way CC does: stdin JSON, env, module dirs."""
    sessions_dir = tmp_path / "sessions"
    flag = tmp_path / "cc_context_enabled"
    flag.touch()
    monkeypatch.setattr(_pc, "_SESSIONS_DIR", sessions_dir)
    monkeypatch.setattr(_pc, "_FLAG", flag)
    monkeypatch.delenv("GENESIS_CC_SESSION", raising=False)
    root = _make_db(tmp_path) if with_db else tmp_path / "repo"
    monkeypatch.setenv("GENESIS_REPO_ROOT", str(root))
    stdin_payload = json.dumps(
        {
            "session_id": session_id,
            "transcript_path": str(transcript),
            "trigger": trigger,
            "hook_event_name": "PreCompact",
        }
    )
    monkeypatch.setattr(_pc.sys, "stdin", io.StringIO(stdin_payload))
    _pc.main()
    return sessions_dir


# ── ledger shadow worker spawn (PR-3) ────────────────────────────────────────


@pytest.fixture(autouse=True)
def spawn_calls(monkeypatch, tmp_path) -> list[list[str]]:
    """AUTOUSE: no test in this module may ever spawn a real worker.

    Replaces subprocess.Popen in the hook module with an argv recorder and
    points the worker err-log inside tmp (never the real home dir).
    """
    calls: list[list[str]] = []

    class _FakeProc:
        pid = 4242

    def _fake_popen(argv, **kwargs):
        calls.append(list(argv))
        assert kwargs.get("start_new_session") is True
        return _FakeProc()

    monkeypatch.setattr(_pc.subprocess, "Popen", _fake_popen)
    monkeypatch.setattr(_pc, "_LEDGER_WORKER_ERR_LOG", tmp_path / "ledger_worker_err.log")
    return calls


def test_spawns_ledger_worker_after_waypoint(monkeypatch, tmp_path, spawn_calls):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    _run_main(monkeypatch, tmp_path, session_id="sid-sp", transcript=t, trigger="auto")
    assert len(spawn_calls) == 1
    argv = spawn_calls[0]
    assert argv[1].endswith("ledger_shadow_worker.py")
    assert argv[argv.index("--session-id") + 1] == "sid-sp"
    assert argv[argv.index("--transcript") + 1] == str(t)
    assert argv[argv.index("--end-byte") + 1] == str(t.stat().st_size)
    assert argv[argv.index("--trigger") + 1] == "auto"


def test_no_spawn_when_dispatched_session(monkeypatch, tmp_path, spawn_calls):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    monkeypatch.setenv("GENESIS_CC_SESSION", "1")
    # _run_main deletes the env var — replicate its harness minus that
    sessions_dir = tmp_path / "sessions"
    monkeypatch.setattr(_pc, "_SESSIONS_DIR", sessions_dir)
    monkeypatch.setattr(
        _pc.sys,
        "stdin",
        io.StringIO(json.dumps({"session_id": "sid-bg", "transcript_path": str(t)})),
    )
    _pc.main()
    assert spawn_calls == []


def test_no_spawn_on_kill_switch(monkeypatch, tmp_path, spawn_calls):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    monkeypatch.setenv("GENESIS_LEDGER_SHADOW_DISABLED", "1")
    _run_main(monkeypatch, tmp_path, session_id="sid-ks", transcript=t)
    assert spawn_calls == []
    # the charter itself still landed — the switch only gates the spawn
    assert _db_row(tmp_path, "sid-ks") is not None


def test_no_spawn_when_charter_failed(monkeypatch, tmp_path, spawn_calls):
    """DB-less run: _update_charter returns None → no waypoint, no spawn."""
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    _run_main(monkeypatch, tmp_path, session_id="sid-nodb", transcript=t, with_db=False)
    assert spawn_calls == []


def test_spawn_failure_never_breaks_hook(monkeypatch, tmp_path):
    def _boom(argv, **kwargs):
        raise OSError("no fds left")

    monkeypatch.setattr(_pc.subprocess, "Popen", _boom)
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    _run_main(monkeypatch, tmp_path, session_id="sid-boom", transcript=t)
    # fail-open: main() returned normally and the charter landed
    assert _db_row(tmp_path, "sid-boom") is not None


def test_first_compaction_creates_charter(monkeypatch, tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    sessions_dir = _run_main(monkeypatch, tmp_path, session_id="sid-1", transcript=t)

    row = _db_row(tmp_path, "sid-1")
    assert row is not None
    assert row["origin_prompt"].startswith("Let's take a look at the flaky retry")
    assert row["compaction_count"] == 1
    assert row["mission"] is None
    assert row["pointers"] == "[]"
    # DB is canonical — charter.json is no longer written
    assert not (sessions_dir / "sid-1" / "charter.json").exists()
    # human mirror + waypoint spine
    md = (sessions_dir / "sid-1" / "charter.md").read_text()
    assert "Let's take a look at the flaky retry" in md
    waypoints = (sessions_dir / "sid-1" / "waypoints.jsonl").read_text().strip().splitlines()
    assert len(waypoints) == 1
    assert json.loads(waypoints[0])["trigger"] == "manual"


def test_second_compaction_bumps_count_origin_immutable(monkeypatch, tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    _run_main(monkeypatch, tmp_path, session_id="sid-1", transcript=t)
    first = _db_row(tmp_path, "sid-1")

    # Transcript head could theoretically change — origin must not.
    _write_transcript(tmp_path / "s.jsonl", [_typed_line("some OTHER prompt")])
    _run_main(monkeypatch, tmp_path, session_id="sid-1", transcript=t, trigger="auto")
    second = _db_row(tmp_path, "sid-1")

    assert second["compaction_count"] == 2
    assert second["origin_prompt"] == first["origin_prompt"]
    assert second["origin_ts"] == first["origin_ts"]
    waypoints = (
        (tmp_path / "sessions" / "sid-1" / "waypoints.jsonl").read_text().strip().splitlines()
    )
    assert [json.loads(w)["trigger"] for w in waypoints] == ["manual", "auto"]


def test_stub_origin_filled_exactly_once(monkeypatch, tmp_path):
    """An MCP write can create the charter row before the first compaction;
    the hook fills origin once and preserves the living fields."""
    root = _make_db(tmp_path)
    conn = sqlite3.connect(root / "data" / "genesis.db")
    conn.execute(
        "INSERT INTO session_charters"
        " (session_id, mission, pointers, compaction_count, created_at)"
        " VALUES ('sid-1', 'pre-set mission', '[\"p1\"]', 0, '2026-07-13T00:00:00+00:00')"
    )
    conn.commit()
    conn.close()

    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    _run_main(monkeypatch, tmp_path, session_id="sid-1", transcript=t)
    row = _db_row(tmp_path, "sid-1")
    assert row["origin_prompt"].startswith("Let's take a look at the flaky retry")
    assert row["compaction_count"] == 1
    assert row["mission"] == "pre-set mission"
    assert row["pointers"] == '["p1"]'
    md = (tmp_path / "sessions" / "sid-1" / "charter.md").read_text()
    assert "pre-set mission" in md

    # A later compaction with a mutated head must not refill origin.
    _write_transcript(tmp_path / "s.jsonl", [_typed_line("some OTHER prompt")])
    _run_main(monkeypatch, tmp_path, session_id="sid-1", transcript=t)
    row2 = _db_row(tmp_path, "sid-1")
    assert row2["origin_prompt"] == row["origin_prompt"]
    assert row2["compaction_count"] == 2


def test_stub_with_promptless_transcript_still_bumps(monkeypatch, tmp_path):
    """Stub row + a transcript with no typed prompt: the compaction is real,
    so the count bumps and origin stays NULL for a later boundary to fill."""
    root = _make_db(tmp_path)
    conn = sqlite3.connect(root / "data" / "genesis.db")
    conn.execute(
        "INSERT INTO session_charters (session_id, pointers, compaction_count, created_at)"
        " VALUES ('sid-1', '[]', 0, '2026-07-13T00:00:00+00:00')"
    )
    conn.commit()
    conn.close()
    t = _write_transcript(tmp_path / "s.jsonl", [_attachment_line(), _tool_result_line()])
    _run_main(monkeypatch, tmp_path, session_id="sid-1", transcript=t)
    row = _db_row(tmp_path, "sid-1")
    assert row["origin_prompt"] is None
    assert row["compaction_count"] == 1


def test_charter_md_includes_ledger(monkeypatch, tmp_path):
    root = _make_db(tmp_path)
    conn = sqlite3.connect(root / "data" / "genesis.db")
    conn.execute(
        "INSERT INTO session_ledger (id, session_id, text, status, added_by, created_at)"
        " VALUES ('l1', 'sid-1', 'open item', 'open', 'foreground', '2026-07-13T00:00:01+00:00')"
    )
    conn.execute(
        "INSERT INTO session_ledger (id, session_id, text, status, added_by, created_at)"
        " VALUES ('l2', 'sid-1', 'done item', 'done', 'foreground', '2026-07-13T00:00:02+00:00')"
    )
    conn.commit()
    conn.close()
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    _run_main(monkeypatch, tmp_path, session_id="sid-1", transcript=t)
    md = (tmp_path / "sessions" / "sid-1" / "charter.md").read_text()
    assert "- [ ] open item" in md
    assert "- [x] done item" in md


def test_renderer_parity_with_canonical():
    """The hook's stdlib _charter_md must render byte-identically to the
    canonical genesis/session_charter.py renderer — drift fails here."""
    from genesis.session_charter import charter_md as canonical

    full = {
        "session_id": "sid-parity",
        "origin_prompt": "The original ask.",
        "origin_ts": "2026-06-30T15:21:06.000Z",
        "mission": "Do the work",
        "pointers": ["p1", "p2"],
        "compaction_count": 4,
        "created_at": "2026-07-13T00:00:00+00:00",
    }
    stub = {"session_id": "sid-stub", "origin_prompt": None, "compaction_count": 0}
    ledger = [
        {"text": "a", "status": "open"},
        {"text": "b", "status": "in_progress"},
        {"text": "c", "status": "done"},
        {"text": "d", "status": "absorbed"},
        {"text": "e", "status": "dropped"},
        {"text": "f", "status": "unknown-status"},
    ]
    assert _pc._charter_md(full, ledger) == canonical(full, ledger)
    assert _pc._charter_md(stub, None) == canonical(stub, None)
    assert _pc._charter_md(full, []) == canonical(full, [])


def test_missing_db_fails_open_and_creates_nothing(monkeypatch, tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    sessions_dir = _run_main(monkeypatch, tmp_path, session_id="sid-1", transcript=t, with_db=False)
    assert not (sessions_dir / "sid-1").exists()
    # The hook must never create a DB file as a side effect
    assert not (tmp_path / "repo" / "data" / "genesis.db").exists()


def test_busy_db_fails_open(monkeypatch, tmp_path):
    """A writer holding the DB lock past busy_timeout → this boundary is
    skipped cleanly (self-heals at the next compaction)."""
    root = _make_db(tmp_path)
    blocker = sqlite3.connect(root / "data" / "genesis.db", timeout=1)
    blocker.isolation_level = None
    blocker.execute("BEGIN IMMEDIATE")
    try:
        t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
        sessions_dir = _run_main(monkeypatch, tmp_path, session_id="sid-1", transcript=t)
        assert not (sessions_dir / "sid-1").exists()  # no md, no waypoint
    finally:
        blocker.execute("ROLLBACK")
        blocker.close()
    assert _db_row(tmp_path, "sid-1") is None


def test_dispatched_session_is_noop(monkeypatch, tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    sessions_dir = tmp_path / "sessions"
    flag = tmp_path / "cc_context_enabled"
    flag.touch()
    monkeypatch.setattr(_pc, "_SESSIONS_DIR", sessions_dir)
    monkeypatch.setattr(_pc, "_FLAG", flag)
    monkeypatch.setenv("GENESIS_REPO_ROOT", str(_make_db(tmp_path)))
    monkeypatch.setenv("GENESIS_CC_SESSION", "1")
    monkeypatch.setattr(
        _pc.sys,
        "stdin",
        io.StringIO(json.dumps({"session_id": "sid-bg", "transcript_path": str(t)})),
    )
    _pc.main()
    assert not (sessions_dir / "sid-bg").exists()
    assert _db_row(tmp_path, "sid-bg") is None


def test_malicious_session_id_rejected(monkeypatch, tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    sessions_dir = _run_main(monkeypatch, tmp_path, session_id="../evil", transcript=t)
    assert not (sessions_dir.parent / "evil").exists()
    assert _db_row(tmp_path, "../evil") is None


def test_missing_transcript_fails_open(monkeypatch, tmp_path):
    sessions_dir = _run_main(
        monkeypatch, tmp_path, session_id="sid-x", transcript=tmp_path / "nope.jsonl"
    )
    # No crash, no partial charter row, no waypoint
    assert _db_row(tmp_path, "sid-x") is None
    assert not (sessions_dir / "sid-x").exists()


def test_context_flag_absent_is_noop(monkeypatch, tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    sessions_dir = tmp_path / "sessions"
    monkeypatch.setattr(_pc, "_SESSIONS_DIR", sessions_dir)
    monkeypatch.setattr(_pc, "_FLAG", tmp_path / "no-such-flag")
    monkeypatch.delenv("GENESIS_CC_SESSION", raising=False)
    monkeypatch.setattr(
        _pc.sys,
        "stdin",
        io.StringIO(json.dumps({"session_id": "sid-1", "transcript_path": str(t)})),
    )
    _pc.main()
    assert not sessions_dir.exists()


# ── SessionStart charter injection ──────────────────────────────────────────
# Existing file-based tests exercise the legacy charter.json FALLBACK path by
# pointing db_path at a nonexistent file; the DB-first tests below exercise
# the canonical path against a real 0058-shaped SQLite file.


def _no_db(tmp_path: Path) -> Path:
    return tmp_path / "absent" / "genesis.db"


def _make_charter(tmp_path: Path, session_id: str, **overrides) -> Path:
    charter = {
        "session_id": session_id,
        "origin_prompt": "Let's take a look at the flaky retry logic in the ingestion pipeline.",
        "origin_ts": "2026-06-30T15:21:06.000Z",
        "created_at": "2026-07-13T02:00:00+00:00",
        "compaction_count": 3,
        "mission": None,
        "pointers": [],
        **overrides,
    }
    session_dir = tmp_path / "sessions" / session_id
    session_dir.mkdir(parents=True, exist_ok=True)
    (session_dir / "charter.json").write_text(json.dumps(charter))
    return tmp_path / "sessions"


def test_charter_block_emitted_from_file_fallback(tmp_path):
    sessions_dir = _make_charter(tmp_path, "sid-1")
    block = _ctx._charter_emission_block(
        "sid-1", "compact", sessions_dir=sessions_dir, db_path=_no_db(tmp_path)
    )
    assert "## Session Charter" in block
    assert "Let's take a look at the flaky retry" in block
    assert "Compactions: 3" in block


def test_charter_block_includes_mission_and_pointers(tmp_path):
    sessions_dir = _make_charter(
        tmp_path,
        "sid-1",
        mission="Ship the session manager",
        pointers=["~/.genesis/output/session-manager-spec-2026-07-13.md"],
    )
    block = _ctx._charter_emission_block(
        "sid-1", "resume", sessions_dir=sessions_dir, db_path=_no_db(tmp_path)
    )
    assert "Ship the session manager" in block
    assert "session-manager-spec-2026-07-13.md" in block


def test_charter_block_empty_when_absent(tmp_path):
    block = _ctx._charter_emission_block(
        "sid-none", "compact", sessions_dir=tmp_path / "sessions", db_path=_no_db(tmp_path)
    )
    assert block == ""


def test_charter_block_empty_on_clear(tmp_path):
    """/clear is an explicit fresh start — never re-assert the old origin."""
    sessions_dir = _make_charter(tmp_path, "sid-1")
    assert (
        _ctx._charter_emission_block(
            "sid-1", "clear", sessions_dir=sessions_dir, db_path=_no_db(tmp_path)
        )
        == ""
    )


def test_charter_block_empty_on_bad_session_id(tmp_path):
    sessions_dir = _make_charter(tmp_path, "sid-1")
    assert (
        _ctx._charter_emission_block(
            "../sid-1", "compact", sessions_dir=sessions_dir, db_path=_no_db(tmp_path)
        )
        == ""
    )
    assert (
        _ctx._charter_emission_block(
            "", "compact", sessions_dir=sessions_dir, db_path=_no_db(tmp_path)
        )
        == ""
    )


def test_charter_block_truncates_long_origin(tmp_path):
    sessions_dir = _make_charter(tmp_path, "sid-1", origin_prompt="x" * 5000)
    block = _ctx._charter_emission_block(
        "sid-1", "compact", sessions_dir=sessions_dir, db_path=_no_db(tmp_path)
    )
    assert "truncated" in block
    assert len(block) < 3000


def test_charter_block_corrupt_json_fails_open(tmp_path):
    session_dir = tmp_path / "sessions" / "sid-1"
    session_dir.mkdir(parents=True)
    (session_dir / "charter.json").write_text("{corrupt")
    assert (
        _ctx._charter_emission_block(
            "sid-1", "compact", sessions_dir=tmp_path / "sessions", db_path=_no_db(tmp_path)
        )
        == ""
    )


# ── DB-first injection path ─────────────────────────────────────────────────


def _seed_db_charter(tmp_path: Path, session_id: str = "sid-db", **overrides) -> Path:
    """0058-shaped tmp DB with a charter row (+ returns the db path)."""
    root = _make_db(tmp_path)
    db_file = root / "data" / "genesis.db"
    row = {
        "session_id": session_id,
        "transcript_path": "/tmp/t.jsonl",
        "origin_prompt": "The DB-canonical origin prompt.",
        "origin_ts": "2026-06-30T15:21:06.000Z",
        "mission": None,
        "pointers": "[]",
        "compaction_count": 5,
        "created_at": "2026-07-13T02:00:00+00:00",
        **overrides,
    }
    conn = sqlite3.connect(db_file)
    conn.execute(
        "INSERT INTO session_charters (session_id, transcript_path, origin_prompt,"
        " origin_ts, mission, pointers, compaction_count, created_at)"
        " VALUES (:session_id, :transcript_path, :origin_prompt, :origin_ts,"
        " :mission, :pointers, :compaction_count, :created_at)",
        row,
    )
    conn.commit()
    conn.close()
    return db_file


def _seed_ledger(db_file: Path, session_id: str, items: list[tuple[str, str, str]]) -> None:
    conn = sqlite3.connect(db_file)
    for i, (item_id, text, status) in enumerate(items):
        conn.execute(
            "INSERT INTO session_ledger (id, session_id, text, status, added_by, created_at)"
            f" VALUES (?, ?, ?, ?, 'foreground', '2026-07-13T00:00:0{i}+00:00')",
            (item_id, session_id, text, status),
        )
    conn.commit()
    conn.close()


def test_charter_block_db_first(tmp_path):
    db_file = _seed_db_charter(
        tmp_path, mission="Ship PR-2a", pointers='["~/.claude/plans/plan.md"]'
    )
    _seed_ledger(
        db_file,
        "sid-db",
        [
            ("l1", "open thing", "open"),
            ("l2", "wip thing", "in_progress"),
            ("l3", "finished thing", "done"),
        ],
    )
    block = _ctx._charter_emission_block(
        "sid-db", "compact", sessions_dir=tmp_path / "sessions", db_path=db_file
    )
    assert "The DB-canonical origin prompt." in block
    assert "**Mission:** Ship PR-2a" in block
    assert "- ~/.claude/plans/plan.md" in block
    assert "- [ ] open thing (id: l1)" in block
    assert "- [~] wip thing (id: l2)" in block
    assert "finished thing" not in block  # closed items stay out of the block
    assert "ledger: 2 open / 1 closed" in block
    assert "Compactions: 5" in block


def test_charter_block_db_beats_stale_file(tmp_path):
    """When both stores have the session, the DB (canonical) wins."""
    db_file = _seed_db_charter(tmp_path, session_id="sid-1")
    _make_charter(tmp_path, "sid-1", origin_prompt="STALE file origin")
    block = _ctx._charter_emission_block(
        "sid-1", "compact", sessions_dir=tmp_path / "sessions", db_path=db_file
    )
    assert "The DB-canonical origin prompt." in block
    assert "STALE file origin" not in block


def test_charter_block_db_stub_falls_back_to_empty(tmp_path):
    """A stub row (origin NULL) has nothing to re-assert yet."""
    db_file = _seed_db_charter(tmp_path, origin_prompt=None)
    block = _ctx._charter_emission_block(
        "sid-db", "compact", sessions_dir=tmp_path / "sessions", db_path=db_file
    )
    assert block == ""


def test_charter_block_db_missing_table_falls_back_to_file(tmp_path):
    """An un-migrated DB (no session_charters table) must not break the
    legacy path — OperationalError → file fallback."""
    empty_db = tmp_path / "repo" / "data" / "genesis.db"
    empty_db.parent.mkdir(parents=True)
    sqlite3.connect(empty_db).close()
    sessions_dir = _make_charter(tmp_path, "sid-1")
    block = _ctx._charter_emission_block(
        "sid-1", "compact", sessions_dir=sessions_dir, db_path=empty_db
    )
    assert "Let's take a look at the flaky retry" in block


def test_charter_block_budget_guard(tmp_path):
    db_file = _seed_db_charter(
        tmp_path,
        origin_prompt="o" * 4000,
        mission="m" * 1000,
        pointers=json.dumps(["p" * 300] * 12),
    )
    _seed_ledger(
        db_file,
        "sid-db",
        [(f"l{i}", "t" * 900, "open") for i in range(6)],
    )
    block = _ctx._charter_emission_block(
        "sid-db", "compact", sessions_dir=tmp_path / "sessions", db_path=db_file
    )
    assert len(block) <= 2900
    assert "truncated" in block
