"""Tests for the PreCompact charter hook + SessionStart charter injection.

Covers scripts/genesis_precompact.py (origin extraction, charter lifecycle,
skip guards, fail-open) and the charter emission block in
scripts/genesis_session_context.py.

Fixture entry shapes mirror REAL transcript entries (verified empirically
against live ~/.claude/projects transcripts, 2026-07-13): typed prompts are
type=="user" with plain-string content; tool results are content-lists of
tool_result blocks; skill/hook injections carry isMeta; compaction summaries
carry isCompactSummary + isVisibleInTranscriptOnly; subagent traffic carries
isSidechain. There is NO promptSource field in real transcripts.
"""

from __future__ import annotations

import importlib.util
import io
import json
from pathlib import Path

# Load the hook scripts as modules (not packages — use importlib)
_SCRIPTS_DIR = Path(__file__).resolve().parent.parent.parent / "scripts"

_pc_spec = importlib.util.spec_from_file_location(
    "genesis_precompact", _SCRIPTS_DIR / "genesis_precompact.py"
)
_pc = importlib.util.module_from_spec(_pc_spec)
_pc_spec.loader.exec_module(_pc)

_ctx_spec = importlib.util.spec_from_file_location(
    "genesis_session_context", _SCRIPTS_DIR / "genesis_session_context.py"
)
_ctx = importlib.util.module_from_spec(_ctx_spec)
_ctx_spec.loader.exec_module(_ctx)


# ── fixture builders (real transcript shapes) ──────────────────────────────


def _attachment_line() -> dict:
    return {"type": "attachment", "attachment": {}, "timestamp": "2026-06-30T15:21:00.000Z"}


def _meta_caveat_line() -> dict:
    return {
        "type": "user",
        "isMeta": True,
        "message": {
            "role": "user",
            "content": "Caveat: The messages below were generated by the user while running local commands.",
        },
        "timestamp": "2026-06-30T15:21:01.000Z",
    }


def _command_line() -> dict:
    return {
        "type": "user",
        "message": {"role": "user", "content": "<command-name>/model</command-name>"},
        "timestamp": "2026-06-30T15:21:02.000Z",
    }


def _tool_result_line() -> dict:
    return {
        "type": "user",
        "message": {
            "role": "user",
            "content": [{"type": "tool_result", "tool_use_id": "x", "content": "ok"}],
        },
        "timestamp": "2026-06-30T15:21:03.000Z",
    }


def _compact_summary_line() -> dict:
    return {
        "type": "user",
        "isCompactSummary": True,
        "isVisibleInTranscriptOnly": True,
        "message": {
            "role": "user",
            "content": "This session is being continued from a previous conversation that ran out of context.",
        },
        "timestamp": "2026-06-30T15:21:04.000Z",
    }


def _sidechain_line() -> dict:
    return {
        "type": "user",
        "isSidechain": True,
        "message": {"role": "user", "content": "subagent prompt text"},
        "timestamp": "2026-06-30T15:21:05.000Z",
    }


def _typed_line(
    text: str = "Let's take a look at the flaky retry logic in the ingestion pipeline.",
) -> dict:
    return {
        "type": "user",
        "isSidechain": False,
        "userType": "external",
        "message": {"role": "user", "content": text},
        "timestamp": "2026-06-30T15:21:06.000Z",
    }


def _write_transcript(path: Path, entries: list[dict]) -> Path:
    path.write_text("\n".join(json.dumps(e) for e in entries) + "\n")
    return path


def _realistic_head(
    typed_text: str = "Let's take a look at the flaky retry logic in the ingestion pipeline.",
) -> list[dict]:
    """The real pre-prompt noise ordering observed in live transcripts."""
    return [
        {"type": "last-prompt", "leafUuid": "x"},
        {"type": "mode", "mode": "default"},
        _attachment_line(),
        _attachment_line(),
        _meta_caveat_line(),
        _command_line(),
        _typed_line(typed_text),
        _tool_result_line(),
    ]


# ── origin extraction ───────────────────────────────────────────────────────


def test_extract_origin_skips_noise_and_finds_first_typed(tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    origin = _pc._extract_origin(t)
    assert origin is not None
    assert origin["origin_prompt"] == (
        "Let's take a look at the flaky retry logic in the ingestion pipeline."
    )
    assert origin["origin_ts"] == "2026-06-30T15:21:06.000Z"


def test_extract_origin_skips_compact_summary_head(tmp_path):
    """A summary-continued session must not charter the summary as origin."""
    entries = [
        _attachment_line(),
        _compact_summary_line(),
        _typed_line("Alright, talk to me about this."),
    ]
    t = _write_transcript(tmp_path / "s.jsonl", entries)
    origin = _pc._extract_origin(t)
    assert origin["origin_prompt"] == "Alright, talk to me about this."


def test_extract_origin_skips_sidechain(tmp_path):
    entries = [_sidechain_line(), _typed_line("real prompt")]
    t = _write_transcript(tmp_path / "s.jsonl", entries)
    assert _pc._extract_origin(t)["origin_prompt"] == "real prompt"


def test_extract_origin_accepts_text_block_list(tmp_path):
    """Typed prompts with attachments arrive as content-block lists."""
    entries = [
        {
            "type": "user",
            "message": {
                "role": "user",
                "content": [
                    {"type": "image", "source": {}},
                    {"type": "text", "text": "what is in this screenshot?"},
                ],
            },
            "timestamp": "2026-06-30T15:21:06.000Z",
        }
    ]
    t = _write_transcript(tmp_path / "s.jsonl", entries)
    assert _pc._extract_origin(t)["origin_prompt"] == "what is in this screenshot?"


def test_extract_origin_none_when_no_typed_prompt(tmp_path):
    entries = [_attachment_line(), _tool_result_line(), _meta_caveat_line()]
    t = _write_transcript(tmp_path / "s.jsonl", entries)
    assert _pc._extract_origin(t) is None


def test_extract_origin_survives_malformed_lines(tmp_path):
    t = tmp_path / "s.jsonl"
    t.write_text('not json at all\n{"type": "mode"}\n' + json.dumps(_typed_line("hi")) + "\n")
    assert _pc._extract_origin(t)["origin_prompt"] == "hi"


# ── charter lifecycle via main() ────────────────────────────────────────────


def _run_main(
    monkeypatch, tmp_path, *, session_id: str, transcript: Path | str, trigger: str = "manual"
):
    """Invoke the hook main() the way CC does: stdin JSON, env, module dirs."""
    sessions_dir = tmp_path / "sessions"
    flag = tmp_path / "cc_context_enabled"
    flag.touch()
    monkeypatch.setattr(_pc, "_SESSIONS_DIR", sessions_dir)
    monkeypatch.setattr(_pc, "_FLAG", flag)
    monkeypatch.delenv("GENESIS_CC_SESSION", raising=False)
    stdin_payload = json.dumps(
        {
            "session_id": session_id,
            "transcript_path": str(transcript),
            "trigger": trigger,
            "hook_event_name": "PreCompact",
        }
    )
    monkeypatch.setattr(_pc.sys, "stdin", io.StringIO(stdin_payload))
    _pc.main()
    return sessions_dir


def test_first_compaction_creates_charter(monkeypatch, tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    sessions_dir = _run_main(monkeypatch, tmp_path, session_id="sid-1", transcript=t)

    charter_file = sessions_dir / "sid-1" / "charter.json"
    assert charter_file.exists()
    charter = json.loads(charter_file.read_text())
    assert charter["origin_prompt"].startswith("Let's take a look at the flaky retry")
    assert charter["compaction_count"] == 1
    assert charter["mission"] is None
    assert charter["pointers"] == []
    # human mirror + waypoint spine
    md = (sessions_dir / "sid-1" / "charter.md").read_text()
    assert "Let's take a look at the flaky retry" in md
    waypoints = (sessions_dir / "sid-1" / "waypoints.jsonl").read_text().strip().splitlines()
    assert len(waypoints) == 1
    assert json.loads(waypoints[0])["trigger"] == "manual"


def test_second_compaction_bumps_count_origin_immutable(monkeypatch, tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    _run_main(monkeypatch, tmp_path, session_id="sid-1", transcript=t)
    first = json.loads((tmp_path / "sessions" / "sid-1" / "charter.json").read_text())

    # Transcript grows and its head could theoretically change — origin must not.
    _write_transcript(tmp_path / "s.jsonl", [_typed_line("some OTHER prompt")])
    _run_main(monkeypatch, tmp_path, session_id="sid-1", transcript=t, trigger="auto")
    second = json.loads((tmp_path / "sessions" / "sid-1" / "charter.json").read_text())

    assert second["compaction_count"] == 2
    assert second["origin_prompt"] == first["origin_prompt"]
    assert second["origin_ts"] == first["origin_ts"]
    waypoints = (
        (tmp_path / "sessions" / "sid-1" / "waypoints.jsonl").read_text().strip().splitlines()
    )
    assert [json.loads(w)["trigger"] for w in waypoints] == ["manual", "auto"]


def test_dispatched_session_is_noop(monkeypatch, tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    sessions_dir = tmp_path / "sessions"
    flag = tmp_path / "cc_context_enabled"
    flag.touch()
    monkeypatch.setattr(_pc, "_SESSIONS_DIR", sessions_dir)
    monkeypatch.setattr(_pc, "_FLAG", flag)
    monkeypatch.setenv("GENESIS_CC_SESSION", "1")
    monkeypatch.setattr(
        _pc.sys,
        "stdin",
        io.StringIO(json.dumps({"session_id": "sid-bg", "transcript_path": str(t)})),
    )
    _pc.main()
    assert not (sessions_dir / "sid-bg").exists()


def test_malicious_session_id_rejected(monkeypatch, tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    sessions_dir = _run_main(monkeypatch, tmp_path, session_id="../evil", transcript=t)
    assert not (sessions_dir.parent / "evil").exists()
    assert not (sessions_dir / ".." / "evil" / "charter.json").resolve().exists()


def test_missing_transcript_fails_open(monkeypatch, tmp_path):
    sessions_dir = _run_main(
        monkeypatch, tmp_path, session_id="sid-x", transcript=tmp_path / "nope.jsonl"
    )
    # No crash, no partial charter, no waypoint
    assert not (sessions_dir / "sid-x" / "charter.json").exists()
    assert not (sessions_dir / "sid-x" / "waypoints.jsonl").exists()


def test_context_flag_absent_is_noop(monkeypatch, tmp_path):
    t = _write_transcript(tmp_path / "s.jsonl", _realistic_head())
    sessions_dir = tmp_path / "sessions"
    monkeypatch.setattr(_pc, "_SESSIONS_DIR", sessions_dir)
    monkeypatch.setattr(_pc, "_FLAG", tmp_path / "no-such-flag")
    monkeypatch.delenv("GENESIS_CC_SESSION", raising=False)
    monkeypatch.setattr(
        _pc.sys,
        "stdin",
        io.StringIO(json.dumps({"session_id": "sid-1", "transcript_path": str(t)})),
    )
    _pc.main()
    assert not sessions_dir.exists()


# ── SessionStart charter injection ──────────────────────────────────────────


def _make_charter(tmp_path: Path, session_id: str, **overrides) -> Path:
    charter = {
        "session_id": session_id,
        "origin_prompt": "Let's take a look at the flaky retry logic in the ingestion pipeline.",
        "origin_ts": "2026-06-30T15:21:06.000Z",
        "created_at": "2026-07-13T02:00:00+00:00",
        "compaction_count": 3,
        "mission": None,
        "pointers": [],
        **overrides,
    }
    session_dir = tmp_path / "sessions" / session_id
    session_dir.mkdir(parents=True, exist_ok=True)
    (session_dir / "charter.json").write_text(json.dumps(charter))
    return tmp_path / "sessions"


def test_charter_block_emitted_when_present(tmp_path):
    sessions_dir = _make_charter(tmp_path, "sid-1")
    block = _ctx._charter_emission_block("sid-1", "compact", sessions_dir=sessions_dir)
    assert "## Session Charter" in block
    assert "Let's take a look at the flaky retry" in block
    assert "Compactions: 3" in block


def test_charter_block_includes_mission_and_pointers(tmp_path):
    sessions_dir = _make_charter(
        tmp_path,
        "sid-1",
        mission="Ship the session manager",
        pointers=["~/.genesis/output/session-manager-spec-2026-07-13.md"],
    )
    block = _ctx._charter_emission_block("sid-1", "resume", sessions_dir=sessions_dir)
    assert "Ship the session manager" in block
    assert "session-manager-spec-2026-07-13.md" in block


def test_charter_block_empty_when_absent(tmp_path):
    block = _ctx._charter_emission_block("sid-none", "compact", sessions_dir=tmp_path / "sessions")
    assert block == ""


def test_charter_block_empty_on_clear(tmp_path):
    """/clear is an explicit fresh start — never re-assert the old origin."""
    sessions_dir = _make_charter(tmp_path, "sid-1")
    assert _ctx._charter_emission_block("sid-1", "clear", sessions_dir=sessions_dir) == ""


def test_charter_block_empty_on_bad_session_id(tmp_path):
    sessions_dir = _make_charter(tmp_path, "sid-1")
    assert _ctx._charter_emission_block("../sid-1", "compact", sessions_dir=sessions_dir) == ""
    assert _ctx._charter_emission_block("", "compact", sessions_dir=sessions_dir) == ""


def test_charter_block_truncates_long_origin(tmp_path):
    sessions_dir = _make_charter(tmp_path, "sid-1", origin_prompt="x" * 5000)
    block = _ctx._charter_emission_block("sid-1", "compact", sessions_dir=sessions_dir)
    assert "truncated" in block
    assert len(block) < 3000


def test_charter_block_corrupt_json_fails_open(tmp_path):
    session_dir = tmp_path / "sessions" / "sid-1"
    session_dir.mkdir(parents=True)
    (session_dir / "charter.json").write_text("{corrupt")
    assert (
        _ctx._charter_emission_block("sid-1", "compact", sessions_dir=tmp_path / "sessions") == ""
    )
