"""Add 'conflicts_pending' to update_history status CHECK constraint.

update.sh's merge-conflict recovery path writes
``status = 'conflicts_pending'`` but the original CHECK constraint
only allowed ('success', 'failed', 'rolled_back'), causing an
IntegrityError that silently dropped conflict-resolution records.

SQLite cannot ALTER CHECK constraints — requires full table rebuild.
"""

from __future__ import annotations

import aiosqlite


async def up(db: aiosqlite.Connection) -> None:
    # Idempotency: check if the fix is already applied
    cursor = await db.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name='update_history'"
    )
    row = await cursor.fetchone()
    if not row:
        return  # Table doesn't exist — fresh install creates it correctly via 0001

    ddl = row[0] or ""
    if "'conflicts_pending'" in ddl:
        return  # Already has the expanded constraint

    # Clean up orphaned temp table from a prior failed attempt
    await db.execute("DROP TABLE IF EXISTS update_history_new")

    await db.execute("""
        CREATE TABLE update_history_new (
            id TEXT PRIMARY KEY,
            old_tag TEXT NOT NULL,
            new_tag TEXT NOT NULL,
            old_commit TEXT NOT NULL,
            new_commit TEXT NOT NULL,
            status TEXT NOT NULL
                CHECK (status IN ('success', 'failed', 'rolled_back', 'conflicts_pending')),
            rollback_tag TEXT,
            failure_reason TEXT,
            degraded_subsystems TEXT,
            started_at TEXT NOT NULL,
            completed_at TEXT NOT NULL
        )
    """)

    await db.execute("""
        INSERT INTO update_history_new
            (id, old_tag, new_tag, old_commit, new_commit, status,
             rollback_tag, failure_reason, degraded_subsystems,
             started_at, completed_at)
        SELECT
            id, old_tag, new_tag, old_commit, new_commit, status,
            rollback_tag, failure_reason, degraded_subsystems,
            started_at, completed_at
        FROM update_history
    """)

    await db.execute("DROP TABLE update_history")
    await db.execute("ALTER TABLE update_history_new RENAME TO update_history")
    # No indexes to recreate — the only index is the PK autoindex
    # (sqlite_autoindex_update_history_1), auto-generated by id TEXT PRIMARY KEY.


async def down(db: aiosqlite.Connection) -> None:
    """Revert to the original 3-status constraint (drops any conflicts_pending rows)."""
    cursor = await db.execute(
        "SELECT sql FROM sqlite_master WHERE type='table' AND name='update_history'"
    )
    row = await cursor.fetchone()
    if not row:
        return

    ddl = row[0] or ""
    if "'conflicts_pending'" not in ddl:
        return  # Already reverted

    await db.execute("DROP TABLE IF EXISTS update_history_new")

    await db.execute("""
        CREATE TABLE update_history_new (
            id TEXT PRIMARY KEY,
            old_tag TEXT NOT NULL,
            new_tag TEXT NOT NULL,
            old_commit TEXT NOT NULL,
            new_commit TEXT NOT NULL,
            status TEXT NOT NULL
                CHECK (status IN ('success', 'failed', 'rolled_back')),
            rollback_tag TEXT,
            failure_reason TEXT,
            degraded_subsystems TEXT,
            started_at TEXT NOT NULL,
            completed_at TEXT NOT NULL
        )
    """)

    # Only copy rows with status values valid under the original constraint
    await db.execute("""
        INSERT INTO update_history_new
            (id, old_tag, new_tag, old_commit, new_commit, status,
             rollback_tag, failure_reason, degraded_subsystems,
             started_at, completed_at)
        SELECT
            id, old_tag, new_tag, old_commit, new_commit, status,
            rollback_tag, failure_reason, degraded_subsystems,
            started_at, completed_at
        FROM update_history
        WHERE status IN ('success', 'failed', 'rolled_back')
    """)

    await db.execute("DROP TABLE update_history")
    await db.execute("ALTER TABLE update_history_new RENAME TO update_history")
