"""Canonical CC transcript parsing for ambient session tooling.

Typed-prompt filtering + byte-windowed delta parsing over the CC
transcript jsonl (session-manager PR-3). The PreCompact hook
(``scripts/genesis_precompact.py``) keeps a private stdlib duplicate of
the typed-prompt filter — it must stay import-free under its 5s budget —
pinned to this module by a parity test (the ``_charter_md`` precedent).

Entry-shape facts (verified against live transcripts, 2026-07-13/14):

- Genuine typed prompts on modern CC (>=2.1.201) carry
  ``promptSource: "typed"`` (or ``"queued"`` when typed mid-turn);
  harness notifications carry ``"system"``; slash-command records
  (``/compact``…) and interrupt markers LACK the key. Older entries (June 2026 heads) have
  no ``promptSource`` at all — so the filter trusts the marker when the
  key is present and falls back to text heuristics when it is absent.
- Typed prompts carry a stable ``uuid`` — the turn ref. Line numbers are
  NOT stable refs (byte-seeks skip torn lines).
- The entry immediately before a typed prompt is almost never assistant
  text (system/mode/attachment/tool_result noise; observed distance 23
  entries, or absent right after a compaction) — snippet extraction
  scans BACK over a bounded window.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

# Content-string prefixes that are NOT typed prompts. Superset of the
# PreCompact hook's list plus the WS-C accumulator's non-thematic
# prefixes (accumulator.py) — command XML, local-command caveats,
# interrupt markers, compaction continuations, bash passthrough.
NON_PROMPT_PREFIXES = (
    "<command-name>",
    "<command-message>",
    "<local-command",
    "Caveat: The messages below were generated by the user",
    "[Request interrupted",
    "This session is being continued",
    "<bash-",
)

# Bare slash-command records ("/compact", "/model") appear as plain
# string content with NO XML wrapper and NO promptSource on some CC
# versions — only a text rule catches them. Single-token only: a real
# prompt that merely starts with "/" ("/etc/hosts is broken") survives.
_SLASH_COMMAND_RE = re.compile(r"^/[A-Za-z][\w:-]*$")

# promptSource values marking genuine human prompts (enumerated across
# 33.9K live user entries, 2026-07-14): "typed" (direct) and "queued"
# (typed while the assistant was mid-turn — ratification messages are
# OVERREPRESENTED here). "system" = harness task-notifications, never a
# prompt; command records lack the key entirely.
_PROMPT_SOURCES = ("typed", "queued")

# Snippet scan-back bound: how many raw entries before a user turn to
# search for the nearest assistant text block (observed real distance:
# 23; absent entirely right after a compaction boundary).
SCANBACK_ENTRIES = 40


def entry_text(content: object) -> str | None:
    """Typed-prompt text from a user entry's message content, else None.

    Plain strings are the common typed-prompt shape. Content-block lists
    are typed prompts only when they carry text blocks and NO
    tool_result blocks (tool results also arrive as type=="user"
    entries with list content).
    """
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        texts: list[str] = []
        for block in content:
            if not isinstance(block, dict):
                return None
            btype = block.get("type")
            if btype == "tool_result":
                return None
            if btype == "text":
                texts.append(str(block.get("text", "")))
        joined = "\n".join(t for t in texts if t).strip()
        return joined or None
    return None


def typed_prompt_text(entry: dict) -> str | None:
    """The typed-prompt text of a transcript entry, or None.

    Filter chain: type=="user"; not sidechain/meta/compact-summary;
    ``promptSource`` honored when the key exists (genuine human prompts
    are "typed"/"queued"; harness notifications "system"; command
    records lack the key); text present; prefix + bare-slash-command
    exclusions.
    """
    if entry.get("type") != "user":
        return None
    if entry.get("isSidechain") or entry.get("isMeta") or entry.get("isCompactSummary"):
        return None
    if "promptSource" in entry and entry.get("promptSource") not in _PROMPT_SOURCES:
        return None
    message = entry.get("message") or {}
    text = entry_text(message.get("content"))
    if not text:
        return None
    stripped = text.lstrip()
    if stripped.startswith(NON_PROMPT_PREFIXES):
        return None
    if _SLASH_COMMAND_RE.match(text.strip()):
        return None
    return text


def _assistant_text(entry: dict) -> str | None:
    """Joined text blocks of an assistant entry, else None."""
    if entry.get("type") != "assistant" or entry.get("isSidechain"):
        return None
    content = (entry.get("message") or {}).get("content")
    if not isinstance(content, list):
        return None
    texts = [
        str(block.get("text", ""))
        for block in content
        if isinstance(block, dict) and block.get("type") == "text"
    ]
    joined = "\n".join(t for t in texts if t).strip()
    return joined or None


def parse_delta(
    transcript_path: Path,
    start_byte: int,
    end_byte: int,
    *,
    max_user_chars: int = 1500,
    max_assistant_chars: int = 500,
    scanback: int = SCANBACK_ENTRIES,
) -> list[dict]:
    """Typed-prompt turns in the byte window ``[start_byte, end_byte]``.

    Returns ``[{turn_ref, ts, user_text, assistant_snippet}]`` oldest
    first. ``turn_ref`` is the entry uuid (fallback: timestamp).
    ``assistant_snippet`` is the nearest preceding assistant text block
    within ``scanback`` entries of the delta ("" when absent — e.g. the
    first turn after a compaction boundary). Both texts are truncated to
    the caps here; quote verification downstream checks against exactly
    what the model saw. Tolerates a torn first line after the seek and
    skips undecodable lines (same tolerance as the hook's origin
    extraction).
    """
    turns: list[dict] = []
    recent: list[dict] = []  # bounded ring of raw entries for scan-back
    with transcript_path.open("rb") as fh:
        if start_byte > 0:
            # Torn-line handling: cursors normally land on a line
            # boundary (st_size at spawn time) — skipping a line there
            # would silently drop a real entry. Peek the byte before
            # start: only a mid-line landing skips the torn remainder.
            fh.seek(start_byte - 1)
            if fh.read(1) != b"\n":
                fh.readline()
        while fh.tell() < end_byte:
            raw = fh.readline()
            if not raw:
                break
            try:
                entry = json.loads(raw)
            except (json.JSONDecodeError, UnicodeDecodeError):
                continue
            if not isinstance(entry, dict):
                continue
            text = typed_prompt_text(entry)
            if text is not None:
                snippet = ""
                for prev in reversed(recent):
                    prev_text = _assistant_text(prev)
                    if prev_text:
                        snippet = prev_text[:max_assistant_chars]
                        break
                turns.append(
                    {
                        "turn_ref": str(entry.get("uuid") or entry.get("timestamp") or ""),
                        "ts": str(entry.get("timestamp", "")),
                        "user_text": text[:max_user_chars],
                        "assistant_snippet": snippet,
                    }
                )
            recent.append(entry)
            if len(recent) > scanback:
                recent.pop(0)
    return turns
