"""Generate ``~/.genesis/release-fingerprints.txt`` — this install's private
leak-detection patterns, derived from local config/environment.

Why this exists
---------------
Leak-detection patterns are DATA with a privacy classification, not neutral
code. A public repo must ship only GENERIC CLASS patterns (all RFC1918, IPv6
ULA per RFC 4193, ``/home/<user>`` shapes — see ``scripts/check_portability.sh``); an
install's SPECIFIC private literals (its hostnames, subnets, ULA prefixes,
private repo name, timezone) must live OUT of the tracked tree. This module
generates those specific literals into the local fingerprint file that
``genesis.contribution.sanitize._check_fingerprints`` already reads (and that
the pre-push + commit-msg hooks consume), so no private byte is ever committed.
See procedure ``public_repo_leak_detection_design``.

Format contract (consumed by three readers — keep it strict)
------------------------------------------------------------
* One pattern per line; blank lines and full-line ``#`` comments are ignored.
  Comments MUST be on their own line — ``sanitize._check_fingerprints`` only
  skips lines that *start* with ``#`` (an inline ``pat # note`` would compile
  the note into the regex).
* **ERE contract:** every emitted pattern must be valid for BOTH Python ``re``
  AND GNU ``grep -E`` (the commit-msg hook greps the file with ``grep -E -f`` on
  Linux dev boxes and GitHub Actions ``ubuntu-latest`` — the only consumers). We
  emit only ``re.escape``'d literals and ``\\b`` (both GNU-supported), never
  ``\\d``/``\\w``/``\\s`` — those are a *literal* ``d``/``w``/``s`` under some
  ``grep -E`` builds, which would silently fail to match → a false-negative leak.

Structure of the managed file::

    # --- BEGIN GENESIS AUTO-GENERATED ... ---
    # <comment for pattern>
    <pattern>
    ...
    # --- END GENESIS AUTO-GENERATED ---

    # Hand-edited patterns below (preserved across regeneration).
    <patterns not derivable from config — e.g. hardware tokens, an AWS
     account prefix — that a human adds once and the generator never touches>

Everything OUTSIDE the marker pair is preserved verbatim on regeneration.

Generalizability
----------------
Runs on any install. Every harvest source is independently guarded — a fresh
public clone with no ``genesis.yaml``, no ``guardian_remote.yaml``, no ``gh``
auth and no ULA addresses produces a valid header-only file (empty harvest,
exit 0) and never fails bootstrap. Secret-sync is opt-in (see ``main``).
"""

from __future__ import annotations

import argparse
import contextlib
import os
import socket
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlsplit

from genesis.util.atomic import atomic_write_text

BEGIN_MARKER = (
    "# --- BEGIN GENESIS AUTO-GENERATED (regenerated by bootstrap; edit OUTSIDE these markers) ---"
)
END_MARKER = "# --- END GENESIS AUTO-GENERATED ---"

_HANDEDIT_HEADER = "# Hand-edited install-specific patterns below (preserved across regeneration)."

#: The Actions secret name the CI private-pattern scan reads (PR 2 consumer).
SECRET_NAME = "GENESIS_PRIVATE_PATTERNS"  # pragma: allowlist secret  # noqa: S105 — the secret's NAME, not a value

#: Tokens too generic to fingerprint — matching them would block huge amounts of
#: legitimate content. The container hostname is literally ``genesis`` and the
#: default user is ``ubuntu``; neither may become a BLOCK pattern.
STOPWORDS = frozenset(
    {
        "ubuntu",
        "root",
        "user",
        "admin",
        "debian",
        "genesis",
        "localhost",
        "host",
        "server",
        "guardian",
        "ambient",
        "default",
        "example",
    }
)

#: Hostnames/IPs that are never install-private (loopback / unspecified).
_HOST_SKIP = frozenset({"127.0.0.1", "0.0.0.0", "localhost", "::1", ""})  # noqa: S104 — skip-list, not a bind address

#: A bare token (hostname, host_user) must clear this length AND not be a
#: stopword before it becomes a live BLOCK pattern. Independent of STOPWORDS so
#: a novel-but-short value (``ns1``) is dropped even though it is not listed.
_MIN_TOKEN_LEN = 5


def _default_path() -> Path:
    """Resolve the fingerprint-file path (mirrors ``sanitize.scan_diff``)."""
    env_path = os.environ.get("GENESIS_RELEASE_FINGERPRINTS")
    if env_path:
        return Path(env_path)
    return Path.home() / ".genesis" / "release-fingerprints.txt"


def _load_yaml(path: Path) -> dict:
    """Best-effort YAML load — returns ``{}`` on any failure (missing file,
    unreadable, malformed, PyYAML absent). Never raises."""
    try:
        import yaml

        with open(path, encoding="utf-8") as f:
            data = yaml.safe_load(f)
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def _escape(literal: str) -> str:
    """ERE- and ``re``-safe escaping of a literal.

    ``re.escape`` only backslash-escapes literal metacharacters; it never emits
    ``\\d``/``\\w``/``\\s``, so its output is valid POSIX ERE. We use it for
    every literal so a value containing ``.``/``-``/``/`` cannot become an
    unintended metacharacter.
    """
    import re

    return re.escape(literal)


def _bounded(literal: str) -> str:
    """Escape ``literal`` and add ``\\b`` ONLY at edges that are word characters.

    A trailing ``\\b`` after a non-word char (e.g. a repo name ending in ``-``)
    can never match — both the punctuation and end-of-string are non-word
    positions — so the pattern would silently fail to block its value. Anchor
    conditionally instead.
    """
    esc = _escape(literal)
    wordish = lambda c: c.isalnum() or c == "_"  # noqa: E731
    left = r"\b" if literal[:1] and wordish(literal[0]) else ""
    right = r"\b" if literal[-1:] and wordish(literal[-1]) else ""
    return left + esc + right


def _specific_token(tok: str) -> bool:
    """True if a bare token is specific enough to fingerprint safely."""
    tok = tok.strip()
    return len(tok) >= _MIN_TOKEN_LEN and tok.lower() not in STOPWORDS


def _ip_prefix_pattern(host: str) -> str | None:
    """A dotted-quad IPv4 host → an escaped ``\\bA.B.C.`` /24-prefix pattern.

    Returns ``None`` for non-IPv4 hosts, loopback/unspecified, or malformed
    input. The prefix (not the full address) is the install signal and matches
    any host on that subnet.
    """
    host = host.strip()
    if host in _HOST_SKIP:
        return None
    parts = host.split(".")
    if len(parts) != 4 or not all(p.isdigit() and 0 <= int(p) <= 255 for p in parts):
        return None
    return r"\b" + _escape(".".join(parts[:3]) + ".")


def _host_from_url(url: str) -> str:
    """Extract the host from a service URL (best effort, '' on failure)."""
    try:
        return urlsplit(url).hostname or ""
    except Exception:
        return ""


def harvest(
    *,
    home: Path | None = None,
    repo_root: Path | None = None,
    run_ip6: bool = True,
) -> list[tuple[str, str]]:
    """Collect ``(pattern, comment)`` pairs from local config/environment.

    Every source is independently guarded — a failure or absence in one yields
    fewer patterns, never an exception. Order is stable for deterministic
    output. Patterns are de-duplicated by pattern string (first comment wins).
    """
    home = home or Path.home()
    if repo_root is None:
        repo_root = Path(__file__).resolve().parents[3]

    out: list[tuple[str, str]] = []

    # 1. Effective service subnets + timezone + private repo name.
    #    We read os.environ directly (rather than importing genesis.env) so
    #    harvest stays home-injectable for tests and free of env.py's config
    #    cache/defaults. Subnet URLs stay env-first (env IS the runtime override
    #    for OLLAMA_URL/LM_STUDIO_URL). Timezone is now FILE-authoritative
    #    (genesis.yaml ``timezone``) with USER_TIMEZONE a deprecated fallback, so
    #    below we block the UNION of both possible tz sources — either could be the
    #    effective runtime zone across installs/versions, and missing the effective
    #    one would leak it. (secrets.env overrides are only seen if bootstrap
    #    exported them into the process.)
    cfg = _load_yaml(home / ".genesis" / "config" / "genesis.yaml")
    try:
        net = cfg.get("network", {}) if isinstance(cfg, dict) else {}
        effective = {
            "ollama_url": os.environ.get("OLLAMA_URL") or str(net.get("ollama_url", "") or ""),
            "lm_studio_url": os.environ.get("LM_STUDIO_URL")
            or str(net.get("lm_studio_url", "") or ""),
        }
        for key, url in effective.items():
            pat = _ip_prefix_pattern(_host_from_url(url))
            if pat:
                out.append((pat, f"private subnet ({key})"))
        for tz in {
            (os.environ.get("USER_TIMEZONE") or "").strip(),
            str(cfg.get("timezone", "") or "").strip(),
        }:
            if tz and tz.upper() != "UTC":
                out.append((_bounded(tz), "install timezone"))
        gh = cfg.get("github", {}) if isinstance(cfg, dict) else {}
        user = str(gh.get("user", "") or "").strip()
        priv = str(gh.get("private_repo", "") or "").strip()
        # Only the user/repo COMBINATION — never the bare user (it appears in
        # the public org name and would mass-false-positive).
        if user and priv:
            out.append((_bounded(f"{user}/{priv}"), "private repo name"))
    except Exception:
        pass

    # 2. guardian/ambient remote yamls — private hostnames + host IPs.
    for name in ("guardian_remote.yaml", "ambient_remote.yaml"):
        remote = _load_yaml(home / ".genesis" / name)
        try:
            hu = str(remote.get("host_user", "") or "").strip()
            if hu and _specific_token(hu):
                out.append((_bounded(hu), f"host user ({name})"))
            pat = _ip_prefix_pattern(str(remote.get("host_ip", "") or ""))
            if pat:
                out.append((pat, f"host subnet ({name})"))
        except Exception:
            pass

    # 3. Live IPv6 ULA prefixes (RFC 4193 — container/host/mesh addresses).
    if run_ip6:
        for prefix in _harvest_ula_prefixes():
            out.append((_escape(prefix), "IPv6 ULA prefix"))

    # 4. $HOME absolute path (covers all /home/<user>/... leaks locally).
    with contextlib.suppress(Exception):
        out.append((_escape(str(home).rstrip("/") + "/"), "home directory path"))

    # 5. CC project-dir slug (e.g. the -home-<user>-genesis transcript slug).
    try:
        slug = str(repo_root).replace("/", "-")
        if len(slug) >= _MIN_TOKEN_LEN:
            out.append((_escape(slug), "CC project-dir slug"))
    except Exception:
        pass

    # 6. Hostname (dropped when it is a stopword like ``genesis``).
    try:
        hn = socket.gethostname().strip()
        if hn and _specific_token(hn):
            out.append((_bounded(hn), "hostname"))
    except Exception:
        pass

    # De-dup by pattern, preserve first-seen order/comment.
    seen: set[str] = set()
    deduped: list[tuple[str, str]] = []
    for pat, comment in out:
        if pat not in seen:
            seen.add(pat)
            deduped.append((pat, comment))
    return deduped


def _harvest_ula_prefixes() -> list[str]:
    """First-two-hextet IPv6 ULA prefixes (RFC 4193) from ``ip -6 addr``.

    Returns ``[]`` if ``ip`` is absent, errors, or times out — never raises.
    """
    try:
        proc = subprocess.run(
            ["ip", "-6", "addr"],
            capture_output=True,
            text=True,
            timeout=3,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return []
    prefixes: list[str] = []
    seen: set[str] = set()
    for line in proc.stdout.splitlines():
        line = line.strip()
        if not line.startswith("inet6 "):
            continue
        addr = line.split()[1].split("/")[0].lower()
        if not addr.startswith(("fc", "fd")):
            continue  # only IPv6 ULA (RFC 4193)
        hextets = addr.split(":")
        if len(hextets) < 2 or not hextets[0] or not hextets[1]:
            continue
        prefix = f"{hextets[0]}:{hextets[1]}"
        if prefix not in seen:
            seen.add(prefix)
            prefixes.append(prefix)
    return prefixes


def build_block(patterns: list[tuple[str, str]]) -> str:
    """Render the marker-delimited AUTO-GENERATED block (no trailing newline)."""
    lines = [BEGIN_MARKER]
    if patterns:
        for pat, comment in patterns:
            lines.append(f"# {comment}")
            lines.append(pat)
    else:
        lines.append("# (no install-specific patterns harvested on this install)")
    lines.append(END_MARKER)
    return "\n".join(lines)


def render(existing: str, block: str) -> str:
    """Splice ``block`` into ``existing``, preserving all hand-edited content.

    * Marker pair present → replace only the region between (and including) the
      markers; preamble and postamble are kept verbatim.
    * No markers (legacy or new file) → the generated block goes first, then a
      hand-edit header, then any prior content preserved as hand-edited.
    """
    lines = existing.splitlines()
    begin = end = None
    for i, ln in enumerate(lines):
        if ln == BEGIN_MARKER and begin is None:
            begin = i
        elif ln == END_MARKER and begin is not None and end is None:
            end = i
            break

    if begin is not None and end is not None:
        before = lines[:begin]
        after = lines[end + 1 :]
        new_lines = before + block.splitlines() + after
        return "\n".join(new_lines).rstrip("\n") + "\n"

    # No marker pair — treat all prior content as hand-edited.
    parts = [block, "", _HANDEDIT_HEADER]
    stripped_existing = existing.strip("\n")
    if stripped_existing:
        parts.append(stripped_existing)
    return "\n".join(parts).rstrip("\n") + "\n"


def generate(path: Path | None = None, **harvest_kwargs) -> tuple[Path, int]:
    """Regenerate the fingerprint file in place. Returns ``(path, n_patterns)``.

    Preserves any hand-edited section. Writes atomically at mode 0600.
    """
    path = path or _default_path()
    patterns = harvest(**harvest_kwargs)
    block = build_block(patterns)
    existing = ""
    if path.is_file():
        try:
            existing = path.read_text(encoding="utf-8")
        except OSError:
            existing = ""
    content = render(existing, block)
    atomic_write_text(path, content)
    # atomic_write_text lands a 0600 temp inode via mkstemp; assert it explicitly.
    with contextlib.suppress(OSError):
        path.chmod(0o600)
    return path, len(patterns)


def _active_patterns(path: Path) -> list[str]:
    """Non-comment, non-blank pattern lines currently in the file."""
    if not path.is_file():
        return []
    out: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s and not s.startswith("#"):
            out.append(s)
    return out


def _resolve_public_slug(repo_root: Path) -> str:
    """The repo the secret belongs on — resolved LIVE from the Genesis repo's
    git remote via ``gh`` (never a config default, which can name the wrong
    repo). ``cwd`` is PINNED to ``repo_root`` so the resolution never depends on
    the caller's ambient working directory (a bootstrap run from elsewhere must
    not target whatever repo the shell happened to be in). '' on failure.
    """
    try:
        proc = subprocess.run(
            ["gh", "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"],
            cwd=str(repo_root),
            capture_output=True,
            text=True,
            timeout=15,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return ""
    return proc.stdout.strip() if proc.returncode == 0 else ""


def _configured_public_repo(home: Path) -> str:
    """The ``github.public_repo`` name from genesis.yaml, or '' if unset."""
    cfg = _load_yaml(home / ".genesis" / "config" / "genesis.yaml")
    gh = cfg.get("github", {}) if isinstance(cfg, dict) else {}
    return str(gh.get("public_repo", "") or "").strip()


def sync_secret(
    path: Path | None = None,
    *,
    repo_root: Path | None = None,
    home: Path | None = None,
) -> bool:
    """Push the active pattern lines to the ``GENESIS_PRIVATE_PATTERNS`` Actions
    secret on the Genesis repo's public remote. Best effort — returns True on a
    successful push, False on any skip (empty patterns, no ``gh``, unauth,
    unresolved/mismatched slug). Never raises. Prints the resolved slug before
    writing.
    """
    home = home or Path.home()
    if repo_root is None:
        repo_root = Path(__file__).resolve().parents[3]
    path = path or _default_path()
    patterns = _active_patterns(path)
    if not patterns:
        print("  fingerprints: no active patterns — skipping secret sync")
        return False
    slug = _resolve_public_slug(repo_root)
    if not slug or "/" not in slug:
        print("  fingerprints: could not resolve public repo slug — skipping secret sync")
        return False
    # Defense in depth: if genesis.yaml names a public_repo, the gh-resolved
    # repo MUST match it — otherwise the repo's origin remote points somewhere
    # unexpected and we must not push private patterns there.
    configured = _configured_public_repo(home)
    if configured and slug.rsplit("/", 1)[-1] != configured:
        print(
            f"  fingerprints: resolved repo {slug} != configured public_repo "
            f"{configured!r} — skipping secret sync (won't push private data to an unexpected repo)"
        )
        return False
    body = "\n".join(patterns) + "\n"
    # Log only the COUNT + target repo — never the patterns themselves (the
    # sensitive value) and not the secret-name variable (CodeQL taints it).
    print(f"  fingerprints: syncing {len(patterns)} pattern(s) to the CI secret on {slug}")
    try:
        proc = subprocess.run(
            # gh reads the secret VALUE from stdin when --body is omitted (there
            # is no --body-file flag); pass it via input= so it never hits argv.
            ["gh", "secret", "set", SECRET_NAME, "--repo", slug],
            input=body,
            capture_output=True,
            text=True,
            timeout=30,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        print(f"  fingerprints: secret sync failed ({exc}) — skipping (non-fatal)")
        return False
    if proc.returncode != 0:
        # Never echo the body; stderr from gh is safe (auth/permission text).
        print(
            f"  fingerprints: secret sync failed (gh: {proc.stderr.strip()[:200]}) — skipping (non-fatal)"
        )
        return False
    return True


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the install fingerprint file.")
    parser.add_argument("--write", action="store_true", help="regenerate the fingerprint file")
    parser.add_argument(
        "--print", dest="do_print", action="store_true", help="print harvested patterns and exit"
    )
    parser.add_argument(
        "--sync-secret", action="store_true", help="regenerate, then sync patterns to the CI secret"
    )
    parser.add_argument(
        "--path", type=Path, default=None, help="override the fingerprint file path"
    )
    args = parser.parse_args(argv)

    if args.do_print:
        for pat, comment in harvest():
            print(f"{pat}\t# {comment}")
        return 0

    # --sync-secret implies a fresh --write so file and secret never drift.
    if args.write or args.sync_secret or not args.do_print:
        path, n = generate(path=args.path)
        print(f"  fingerprints: wrote {n} install pattern(s) to {path}")

    if args.sync_secret:
        sync_secret(path=args.path)

    return 0


if __name__ == "__main__":
    sys.exit(main())
