#!/usr/bin/env python3
"""PreCompact hook: persist the session charter at every compaction boundary.

The charter-session model: compaction implies continuity — nobody compacts to
change topic, so the pre-first-compaction window is the session's golden
context. At the FIRST compaction boundary — while the full-fidelity transcript
is still on disk — this hook extracts the session's IMMUTABLE origin (the
first typed user prompt) into ~/.genesis/sessions/<session_id>/charter.json.
At EVERY compaction it bumps the compaction count and appends a deterministic
waypoint to waypoints.jsonl. The SessionStart hook
(genesis_session_context.py) re-injects the charter into every
post-compaction window, so no recency-biased summary can erase what the
session is FOR.

Charter fields:
- origin_prompt / origin_ts — IMMUTABLE once written, never regenerated.
- mission / pointers — living fields, written by later session-manager
  stages (ledger MCP tools); this hook preserves them verbatim on update.

Registered in .claude/settings.json under PreCompact (fires on both manual
and auto compaction, timeout 5s). Fail-open by design: always exits 0 — a
hook failure must never block compaction (exit 2 would cancel it).

Foreground interactive sessions only: dispatched sessions
(GENESIS_CC_SESSION=1) keep task_states as their continuity spine.
"""

from __future__ import annotations

import json
import os
import sys
from datetime import UTC, datetime
from pathlib import Path

_FLAG = Path.home() / ".genesis" / "cc_context_enabled"
_SESSIONS_DIR = Path.home() / ".genesis" / "sessions"

# Bound the stored origin: real typed prompts are far shorter; a pasted-wall
# first prompt still yields a useful (truncated) charter.
_ORIGIN_MAX_CHARS = 4000

# Content-string prefixes that are NOT typed prompts. Command invocations
# (/model, /compact, ...) land as <command-name>/<command-message>/
# <local-command-stdout> XML-ish strings; CC also injects a caveat line for
# local-command output. (Shapes verified against live transcripts 2026-07-13.)
_NON_PROMPT_PREFIXES = (
    "<command-name>",
    "<command-message>",
    "<local-command",
    "Caveat: The messages below were generated by the user",
)


def _entry_text(content: object) -> str | None:
    """Typed-prompt text from a user entry's message content, else None.

    Plain strings are the common typed-prompt shape. Content-block lists are
    typed prompts only when they carry text blocks and NO tool_result blocks
    (tool results also arrive as type=="user" entries with list content).
    """
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        texts: list[str] = []
        for block in content:
            if not isinstance(block, dict):
                return None
            btype = block.get("type")
            if btype == "tool_result":
                return None
            if btype == "text":
                texts.append(str(block.get("text", "")))
        joined = "\n".join(t for t in texts if t).strip()
        return joined or None
    return None


def _extract_origin(transcript_path: Path) -> dict | None:
    """First typed user prompt in the transcript head — the immutable origin.

    Streams the file and stops at the first hit, so cost is bounded by the
    pre-prompt noise (attachments, mode lines), not transcript size. Skips
    subagent traffic (isSidechain), hook/skill injections (isMeta), and
    compaction summaries (isCompactSummary) — a summary-continued session
    must never charter the summary text as its origin.
    """
    with transcript_path.open(encoding="utf-8") as fh:
        for line in fh:
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue
            if entry.get("type") != "user":
                continue
            if entry.get("isSidechain") or entry.get("isMeta") or entry.get("isCompactSummary"):
                continue
            message = entry.get("message") or {}
            text = _entry_text(message.get("content"))
            if not text:
                continue
            if text.lstrip().startswith(_NON_PROMPT_PREFIXES):
                continue
            return {
                "origin_prompt": text[:_ORIGIN_MAX_CHARS],
                "origin_ts": str(entry.get("timestamp", "")),
            }
    return None


def _charter_md(charter: dict) -> str:
    """Human-readable mirror of charter.json (regenerated on every update)."""
    lines = [
        f"# Session Charter — {charter.get('session_id', '')}",
        "",
        f"- **Born:** {charter.get('origin_ts') or 'unknown'}",
        f"- **Compactions:** {charter.get('compaction_count', 0)}",
        f"- **Charter created:** {charter.get('created_at', '')}",
        "",
        "## Origin (immutable)",
        "",
        str(charter.get("origin_prompt", "")),
    ]
    mission = charter.get("mission")
    if mission:
        lines += ["", "## Mission", "", str(mission)]
    pointers = charter.get("pointers") or []
    if pointers:
        lines += ["", "## Pointers", ""]
        lines += [f"- {p}" for p in pointers]
    return "\n".join(lines) + "\n"


def _update_charter(session_dir: Path, session_id: str, transcript_path: str) -> dict | None:
    """Create the charter at the first boundary; bump the count thereafter.

    Returns the written charter, or None when there is nothing to charter yet
    (no typed prompt found — e.g. a session compacted before any real turn).
    origin_prompt/origin_ts are written exactly once and never regenerated;
    mission/pointers written by other components are preserved verbatim.
    """
    charter_file = session_dir / "charter.json"
    now = datetime.now(UTC).isoformat()
    if charter_file.exists():
        charter = json.loads(charter_file.read_text(encoding="utf-8"))
        charter["compaction_count"] = int(charter.get("compaction_count", 0)) + 1
        charter["updated_at"] = now
    else:
        origin = _extract_origin(Path(transcript_path))
        if origin is None:
            return None
        charter = {
            "session_id": session_id,
            "transcript_path": transcript_path,
            "created_at": now,
            "compaction_count": 1,
            "mission": None,
            "pointers": [],
            **origin,
        }
    session_dir.mkdir(parents=True, exist_ok=True)
    charter_file.write_text(json.dumps(charter, indent=2), encoding="utf-8")
    (session_dir / "charter.md").write_text(_charter_md(charter), encoding="utf-8")
    return charter


def _append_waypoint(session_dir: Path, trigger: str, transcript_path: str) -> None:
    """Append the deterministic waypoint spine (semantic waypoints come later).

    transcript_bytes uses stat (free) rather than a line count — a full-file
    read on a multi-week transcript would burn the 5s hook budget for a
    marginally better metric.
    """
    try:
        size: int | None = Path(transcript_path).stat().st_size
    except OSError:
        size = None
    waypoint = {
        "ts": datetime.now(UTC).isoformat(),
        "trigger": trigger,
        "transcript_bytes": size,
    }
    with (session_dir / "waypoints.jsonl").open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(waypoint) + "\n")


def main() -> None:
    # Fail-open: this hook must NEVER block compaction. Any failure logs to
    # stderr and returns; the __main__ wrapper always exits 0.
    try:
        # Eject lever shared with all Genesis session hooks
        if not _FLAG.exists():
            return
        # Dispatched sessions keep task_states as their continuity spine
        if os.environ.get("GENESIS_CC_SESSION") == "1":
            return

        try:
            raw = sys.stdin.read()
            hook_input = json.loads(raw) if raw.strip() else {}
        except (json.JSONDecodeError, OSError):
            hook_input = {}

        session_id = str(hook_input.get("session_id", "") or "")
        transcript_path = str(hook_input.get("transcript_path", "") or "")
        trigger = str(hook_input.get("trigger", "") or "unknown")
        if not session_id or not transcript_path:
            return
        # Path-injection guard (session_id becomes a directory component)
        if "/" in session_id or ".." in session_id:
            return

        session_dir = _SESSIONS_DIR / session_id
        charter = _update_charter(session_dir, session_id, transcript_path)
        if charter is not None:
            _append_waypoint(session_dir, trigger, transcript_path)
    except Exception as exc:  # noqa: BLE001 — fail-open boundary
        print(f"genesis_precompact failed (fail-open): {exc}", file=sys.stderr)


if __name__ == "__main__":
    main()
    sys.exit(0)
