"""Dashboard route modules — all routes are registered on the blueprint defined in _blueprint."""

from __future__ import annotations

from genesis.dashboard.routes import (
    activity,
    backup,
    budget,
    config,
    ego,
    errors,
    events,
    files,
    follow_ups,
    health,
    knowledge,
    knowledge_upload,
    memory,
    modules,
    outreach,
    pause,
    providers,
    recon,
    resolution,
    routing,
    secrets,
    services,
    settings,
    state,
    stream,
    surplus,
    tasks,
    terminal,
    ui_data,
    updates,
    vitals,
)

__all__ = [
    "activity",
    "backup",
    "budget",
    "config",
    "ego",
    "errors",
    "events",
    "files",
    "follow_ups",
    "health",
    "knowledge",
    "knowledge_upload",
    "memory",
    "modules",
    "outreach",
    "pause",
    "providers",
    "recon",
    "resolution",
    "routing",
    "secrets",
    "services",
    "settings",
    "state",
    "stream",
    "surplus",
    "tasks",
    "terminal",
    "ui_data",
    "updates",
    "vitals",
]
